/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description 가입 신청. 승인 전까지는 로그인할 수 없다(status=pending).
         */
        post: operations["signup_api_accounts_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description 계정을 지운다. 행은 남고 접근만 끊긴다 — 자료의 소유자 참조를 잃지 않기 위해서다.
         */
        delete: operations["delete_account_api_accounts__account_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate */
        post: operations["activate_api_accounts__account_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_accounts__account_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/dependents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dependents
         * @description 삭제 전 미리보기. 무엇이 딸려 있는지 보고 나서 결정하게 한다.
         */
        get: operations["dependents_api_accounts__account_id__dependents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_accounts__account_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description 관리자 중개 재설정. SMTP 가 없으므로 화면에 1회 표시하고 구두로 전달한다.
         */
        post: operations["reset_password_api_accounts__account_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend */
        post: operations["suspend_api_accounts__account_id__suspend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tokens */
        get: operations["list_tokens_api_auth_tokens_get"];
        put?: never;
        /** Create Token */
        post: operations["create_token_api_auth_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/tokens/{pat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Token */
        delete: operations["revoke_token_api_auth_tokens__pat_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Materials */
        get: operations["list_materials_api_materials_get"];
        put?: never;
        /** Create Material */
        post: operations["create_material_api_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/preview-name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Name
         * @description 등록 폼이 입력 중에 부른다.
         *
         *     이름을 만드는 곳은 서버 하나다. 화면이 같은 규칙을 다시 구현하면 두 구현이
         *     갈라지고, 그때 화면이 보여 준 이름과 저장된 이름이 달라진다.
         */
        post: operations["preview_name_api_materials_preview_name_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material */
        get: operations["get_material_api_materials__material_id__get"];
        put?: never;
        post?: never;
        /** Delete Material */
        delete: operations["delete_material_api_materials__material_id__delete"];
        options?: never;
        head?: never;
        /** Update Material */
        patch: operations["update_material_api_materials__material_id__patch"];
        trace?: never;
    };
    "/api/materials/{material_id}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Samples */
        get: operations["list_samples_api_materials__material_id__samples_get"];
        put?: never;
        /** Create Sample */
        post: operations["create_sample_api_materials__material_id__samples_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notices */
        get: operations["list_notices_api_notices_get"];
        put?: never;
        /** Create Notice */
        post: operations["create_notice_api_notices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notices/popup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Popup Notices
         * @description 로그인 후 한 번 띄울 공지. 읽은 것은 빠진다.
         */
        get: operations["popup_notices_api_notices_popup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notices/{notice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Notice */
        patch: operations["update_notice_api_notices__notice_id__patch"];
        trace?: never;
    };
    "/api/notices/{notice_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_api_notices__notice_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_api_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread Count */
        get: operations["unread_count_api_notifications_unread_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_api_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sample */
        get: operations["get_sample_api_samples__sample_id__get"];
        put?: never;
        post?: never;
        /** Delete Sample */
        delete: operations["delete_sample_api_samples__sample_id__delete"];
        options?: never;
        head?: never;
        /** Update Sample */
        patch: operations["update_sample_api_samples__sample_id__patch"];
        trace?: never;
    };
    "/api/samples/{sample_id}/specimens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Specimens */
        get: operations["list_specimens_api_samples__sample_id__specimens_get"];
        put?: never;
        /** Create Specimen */
        post: operations["create_specimen_api_samples__sample_id__specimens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/specimens/{specimen_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Specimen */
        get: operations["get_specimen_api_specimens__specimen_id__get"];
        put?: never;
        post?: never;
        /** Delete Specimen */
        delete: operations["delete_specimen_api_specimens__specimen_id__delete"];
        options?: never;
        head?: never;
        /** Update Specimen */
        patch: operations["update_specimen_api_specimens__specimen_id__patch"];
        trace?: never;
    };
    "/api/voc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_voc_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_voc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voc/{item_id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reply */
        post: operations["reply_api_voc__item_id__reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_api_workspaces_get"];
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_api_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Options
         * @description 가입 신청 화면용. 로그인 전에 부르므로 인증이 없다.
         */
        get: operations["options_api_workspaces_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Workspace */
        patch: operations["update_workspace_api_workspaces__slug__patch"];
        trace?: never;
    };
    "/api/workspaces/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_workspaces__slug__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_api_workspaces__slug__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{slug}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_workspaces__slug__members__user_id__delete"];
        options?: never;
        head?: never;
        /** Set Member Role */
        patch: operations["set_member_role_api_workspaces__slug__members__user_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountOut */
        AccountOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Decision Note */
            decision_note: string | null;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Home Workspace Slug */
            home_workspace_slug: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is System Admin */
            is_system_admin: boolean;
            /** Memberships */
            memberships: string[];
            /** Must Change Password */
            must_change_password: boolean;
            /** Requested Workspace Slug */
            requested_workspace_slug: string | null;
            /** Status */
            status: string;
        };
        /** ApproveRequest */
        ApproveRequest: {
            /**
             * Role
             * @default member
             */
            role: string;
            /** Workspace Slug */
            workspace_slug?: string | null;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * CreateAccountRequest
         * @description 관리자가 직접 계정을 만들 때. 승인 절차 없이 바로 활성이다.
         */
        CreateAccountRequest: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Is System Admin
             * @default false
             */
            is_system_admin: boolean;
            /**
             * Role
             * @default member
             */
            role: string;
            /** Workspace Slug */
            workspace_slug: string;
        };
        /** DeleteAccountRequest */
        DeleteAccountRequest: {
            /** Transfer To Id */
            transfer_to_id?: string | null;
        };
        /** DeleteAccountResponse */
        DeleteAccountResponse: {
            /** Transferred */
            transferred: components["schemas"]["ReferenceOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserOut"];
        };
        /** MaterialCreateRequest */
        MaterialCreateRequest: {
            /** Alias */
            alias?: string | null;
            /** Category */
            category: string;
            /** Details */
            details?: string | null;
            /** Family */
            family: string;
            /** Grade */
            grade: string;
            /** Legacy Id */
            legacy_id?: string | null;
            /** Note */
            note?: string | null;
            /** Spec Thickness */
            spec_thickness?: number | null;
            /**
             * Spec Thickness Unit
             * @default mm
             */
            spec_thickness_unit: string;
            /** Workspace Slug */
            workspace_slug?: string | null;
        };
        /** MaterialOut */
        MaterialOut: {
            /** Alias */
            alias: string | null;
            /** Category */
            category: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Details */
            details: string | null;
            /** Family */
            family: string;
            /** Grade */
            grade: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Global */
            is_global: boolean;
            /** Legacy Id */
            legacy_id: string | null;
            /** Note */
            note: string | null;
            /** Owner Workspace Id */
            owner_workspace_id: string | null;
            /** Owner Workspace Name */
            owner_workspace_name: string | null;
            /** Record Name */
            record_name: string;
            /** Sample Count */
            sample_count: number;
            /** Spec Thickness */
            spec_thickness: number | null;
            /**
             * Spec Thickness Unit
             * @default mm
             */
            spec_thickness_unit: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MaterialUpdateRequest */
        MaterialUpdateRequest: {
            /** Alias */
            alias?: string | null;
            /** Category */
            category?: string | null;
            /** Details */
            details?: string | null;
            /** Family */
            family?: string | null;
            /** Grade */
            grade?: string | null;
            /** Note */
            note?: string | null;
            /** Spec Thickness */
            spec_thickness?: number | null;
            /** Spec Thickness Unit */
            spec_thickness_unit?: string | null;
        };
        /** MemberAddRequest */
        MemberAddRequest: {
            /** Email */
            email: string;
            /**
             * Role
             * @default member
             */
            role: string;
        };
        /** MemberOut */
        MemberOut: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MemberRoleRequest */
        MemberRoleRequest: {
            /** Role */
            role: string;
        };
        /** NamePreviewOut */
        NamePreviewOut: {
            /** Record Name */
            record_name: string;
            /** Taken */
            taken: boolean;
        };
        /**
         * NamePreviewRequest
         * @description 등록 폼이 입력 중에 부르는 것. 서버가 이름을 만드는 유일한 곳이므로,
         *     화면이 같은 규칙을 다시 구현하지 않게 한다.
         */
        NamePreviewRequest: {
            /** Details */
            details?: string | null;
            /** Grade */
            grade?: string | null;
            /** Spec Thickness */
            spec_thickness?: number | null;
            /**
             * Spec Thickness Unit
             * @default mm
             */
            spec_thickness_unit: string;
        };
        /** NoticeCreateRequest */
        NoticeCreateRequest: {
            /** Body */
            body: string;
            /**
             * Is Popup
             * @default false
             */
            is_popup: boolean;
            /**
             * Is Published
             * @default true
             */
            is_published: boolean;
            /** Title */
            title: string;
        };
        /** NoticeOut */
        NoticeOut: {
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Popup */
            is_popup: boolean;
            /** Is Published */
            is_published: boolean;
            /** Is Read */
            is_read: boolean;
            /** Published At */
            published_at: string | null;
            /** Title */
            title: string;
        };
        /** NoticeUpdateRequest */
        NoticeUpdateRequest: {
            /** Body */
            body?: string | null;
            /** Is Popup */
            is_popup?: boolean | null;
            /** Is Published */
            is_published?: boolean | null;
            /** Title */
            title?: string | null;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Body */
            body: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Event Kind */
            event_kind: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Link */
            link: string | null;
            /** Read At */
            read_at: string | null;
            /** Title */
            title: string;
        };
        /** Page[MaterialOut] */
        Page_MaterialOut_: {
            /** Items */
            items: components["schemas"]["MaterialOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PatCreateRequest */
        PatCreateRequest: {
            /** Expires In Days */
            expires_in_days?: number | null;
            /** Name */
            name: string;
        };
        /** PatCreateResponse */
        PatCreateResponse: {
            pat: components["schemas"]["PatOut"];
            /** Token */
            token: string;
        };
        /** PatOut */
        PatOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /** Revoked At */
            revoked_at: string | null;
        };
        /**
         * ReferenceOut
         * @description 이 계정을 가리키는 참조 하나. 삭제 전에 보여 준다.
         */
        ReferenceOut: {
            /** Blocks Delete */
            blocks_delete: boolean;
            /** Column */
            column: string;
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** On Delete */
            on_delete: string | null;
            /** Table */
            table: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /** Note */
            note: string;
        };
        /** SampleCreateRequest */
        SampleCreateRequest: {
            /** Alias */
            alias?: string | null;
            /** Applied Part */
            applied_part?: string | null;
            /** Applied Product */
            applied_product?: string | null;
            /** Density */
            density?: number | null;
            /**
             * Density Unit
             * @default kg/m3
             */
            density_unit: string;
            /** Distributor */
            distributor?: string | null;
            /** Lot No */
            lot_no?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Note */
            note?: string | null;
            /** Poisson Ratio */
            poisson_ratio?: number | null;
            /** Primary Vendor */
            primary_vendor?: string | null;
            /** Production Date */
            production_date?: string | null;
            /** Sales Type */
            sales_type?: string | null;
            /** Workspace Slug */
            workspace_slug?: string | null;
        };
        /** SampleOut */
        SampleOut: {
            /** Alias */
            alias: string | null;
            /** Applied Part */
            applied_part: string | null;
            /** Applied Product */
            applied_product: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Density */
            density: number | null;
            /**
             * Density Unit
             * @default kg/m3
             */
            density_unit: string;
            /** Distributor */
            distributor: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lot No */
            lot_no: string | null;
            /** Manufacturer */
            manufacturer: string | null;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Note */
            note: string | null;
            /** Poisson Ratio */
            poisson_ratio: number | null;
            /** Primary Vendor */
            primary_vendor: string | null;
            /** Production Date */
            production_date: string | null;
            /** Record Name */
            record_name: string;
            /** Sales Type */
            sales_type: string | null;
            /** Seq No */
            seq_no: number;
            /** Specimen Count */
            specimen_count: number;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Workspace Name */
            workspace_name: string | null;
        };
        /** SampleUpdateRequest */
        SampleUpdateRequest: {
            /** Alias */
            alias?: string | null;
            /** Applied Part */
            applied_part?: string | null;
            /** Applied Product */
            applied_product?: string | null;
            /** Density */
            density?: number | null;
            /** Density Unit */
            density_unit?: string | null;
            /** Distributor */
            distributor?: string | null;
            /** Lot No */
            lot_no?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Note */
            note?: string | null;
            /** Poisson Ratio */
            poisson_ratio?: number | null;
            /** Primary Vendor */
            primary_vendor?: string | null;
            /** Production Date */
            production_date?: string | null;
            /** Sales Type */
            sales_type?: string | null;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Workspace Slug */
            workspace_slug: string;
        };
        /** SpecimenCreateRequest */
        SpecimenCreateRequest: {
            /** Gauge Length */
            gauge_length?: number | null;
            /**
             * Length Unit
             * @default mm
             */
            length_unit: string;
            /** Note */
            note?: string | null;
            /**
             * Orientation
             * @default NA
             */
            orientation: string;
            /** Seq No */
            seq_no?: number | null;
            /** Thickness */
            thickness?: number | null;
            /** Width */
            width?: number | null;
        };
        /** SpecimenOut */
        SpecimenOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Gauge Length */
            gauge_length: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Length Unit
             * @default mm
             */
            length_unit: string;
            /** Note */
            note: string | null;
            /** Orientation */
            orientation: string;
            /** Record Name */
            record_name: string;
            /**
             * Sample Id
             * Format: uuid
             */
            sample_id: string;
            /** Seq No */
            seq_no: number;
            /** Thickness */
            thickness: number | null;
            /** Width */
            width: number | null;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** SpecimenUpdateRequest */
        SpecimenUpdateRequest: {
            /** Gauge Length */
            gauge_length?: number | null;
            /** Length Unit */
            length_unit?: string | null;
            /** Note */
            note?: string | null;
            /** Thickness */
            thickness?: number | null;
            /** Width */
            width?: number | null;
        };
        /**
         * TemporaryPasswordResponse
         * @description 임시 비밀번호는 이 응답에서 한 번만 나온다.
         *
         *     SMTP 가 없어 메일로 보낼 수 없으므로, 관리자가 화면에서 읽어 구두·메신저로
         *     전달한다. 받는 사람은 첫 로그인 때 변경이 강제된다.
         */
        TemporaryPasswordResponse: {
            account: components["schemas"]["AccountOut"];
            /** Temporary Password */
            temporary_password: string;
        };
        /** UnreadCountOut */
        UnreadCountOut: {
            /** Unread */
            unread: number;
        };
        /** UserOut */
        UserOut: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Home Workspace Slug */
            home_workspace_slug: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is System Admin */
            is_system_admin: boolean;
            /** Memberships */
            memberships: components["schemas"]["WorkspaceMembershipOut"][];
            /** Must Change Password */
            must_change_password: boolean;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VocCreateRequest */
        VocCreateRequest: {
            /** Body */
            body: string;
            /** Page Path */
            page_path?: string | null;
            /** Title */
            title: string;
        };
        /** VocOut */
        VocOut: {
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Page Path */
            page_path: string | null;
            /** Replied At */
            replied_at: string | null;
            /** Reply */
            reply: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** VocReplyRequest */
        VocReplyRequest: {
            /** Reply */
            reply: string;
            /**
             * Status
             * @default resolved
             */
            status: string;
        };
        /** WorkspaceCreateRequest */
        WorkspaceCreateRequest: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** WorkspaceMembershipOut */
        WorkspaceMembershipOut: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Slug */
            slug: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * WorkspaceOption
         * @description 가입 화면에서 희망 부서를 고르기 위한 최소 정보. 인증 없이 노출된다.
         */
        WorkspaceOption: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Kind */
            kind: string;
            /** Member Count */
            member_count: number;
            /** My Role */
            my_role: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** WorkspaceUpdateRequest */
        WorkspaceUpdateRequest: {
            /** Is Active */
            is_active?: boolean | null;
            /** Name */
            name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_api_accounts_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_api_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemporaryPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_accounts_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_api_accounts__account_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_accounts__account_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dependents_api_accounts__account_id__dependents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_accounts__account_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_accounts__account_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemporaryPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspend_api_accounts__account_id__suspend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    list_tokens_api_auth_tokens_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatOut"][];
                };
            };
        };
    };
    create_token_api_auth_tokens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_token_api_auth_tokens__pat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_materials_api_materials_get: {
        parameters: {
            query?: {
                /** @description 이름·별칭·Grade 부분 일치 */
                q?: string | null;
                family?: string | null;
                category?: string | null;
                scope?: string;
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MaterialOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_material_api_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_name_api_materials_preview_name_post: {
        parameters: {
            query?: {
                workspace_slug?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamePreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_api_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_material_api_materials__material_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_material_api_materials__material_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_samples_api_materials__material_id__samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sample_api_materials__material_id__samples_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notices_api_notices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticeOut"][];
                };
            };
        };
    };
    create_notice_api_notices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    popup_notices_api_notices_popup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticeOut"][];
                };
            };
        };
    };
    update_notice_api_notices__notice_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notice_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticeUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_api_notices__notice_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_api_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCountOut"];
                };
            };
        };
    };
    unread_count_api_notifications_unread_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCountOut"];
                };
            };
        };
    };
    mark_read_api_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sample_api_samples__sample_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sample_api_samples__sample_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_sample_api_samples__sample_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_specimens_api_samples__sample_id__specimens_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_specimen_api_samples__sample_id__specimens_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecimenCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_specimen_api_specimens__specimen_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specimen_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_specimen_api_specimens__specimen_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specimen_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_specimen_api_specimens__specimen_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specimen_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecimenUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_voc_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_voc_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reply_api_voc__item_id__reply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_api_workspaces_get: {
        parameters: {
            query?: {
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workspace_api_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_api_workspaces_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOption"][];
                };
            };
        };
    };
    update_workspace_api_workspaces__slug__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_workspaces__slug__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_workspaces__slug__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_workspaces__slug__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_member_role_api_workspaces__slug__members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
