"""여러 솔버의 실제 덱을 읽는다 — **이 창구가 열리는 솔버가 몇 개인가.**

`test_export_scan.py` 가 읽는 규칙 하나하나를 보는 곳이라면, 여기는 **덱 한 벌씩**
을 통째로 먹여 「이 솔버는 붙일 만한가」 에 답한다. 붙일 만하다는 것은 초안이
대체로 맞아서 **사람이 값 이름만 채우면 되는** 상태를 뜻한다.

무는 자리는 솔버마다 다르지만 성격은 하나다 — **칸이 하나 늘거나 줄면 그 덱은
모든 값이 밀린 채로 나가고, 솔버는 그것을 오류로 알려 주지 않는다.**

실측(2026-08-30)으로 여기서 다섯을 잡았다:

    Nastran 축약 지수      `7.85-9` 를 `7.85` 와 `-9` 로 읽었다. 값도 칸 수도 틀렸다.
    Nastran 왼쪽 맞춤      `MAT1` 이 첫 칸을 차지해 폭을 못 쟀다.
    ANSYS 세 물성이 한 표    `MP,EX`·`MP,PRXY`·`MP,DENS` 가 숫자 개수만 같아 묶였다 —
                          **두 줄이 사라졌다.**
    접두 글자를 담을 데 없음   `MP,EX,`·`MAT1` 을 못 적으면 그 솔버는 아예 못 붙인다.
    고정폭의 앞 공백        첫 칸의 패딩인데 접두로 잡혀 줄이 두 번 밀렸다.
"""

from __future__ import annotations

from matcore.export import scan

ABAQUS = """*MATERIAL, NAME=STEEL
*ELASTIC
210000., 0.3
*PLASTIC
250., 0.
300., 0.02
340., 0.05
*DENSITY
7.85E-09,
"""

#: HyperMesh 가 낸 Abaqus. 머리에 주석이 붙고 버전 번호가 들어 있다.
HM_ABAQUS = """**HM_ADD_COMMENTS
**  Abaqus Input Deck Generated by HyperMesh Version : 2021
*MATERIAL, NAME=steel
*ELASTIC, TYPE=ISOTROPIC
210000., 0.3, 20.
190000., 0.31, 200.
170000., 0.32, 400.
"""

#: Nastran / OptiStruct 벌크 데이터. **고정 8칸 왼쪽 맞춤**이고 지수의 `E` 가 없다.
NASTRAN = """$ HyperMesh
MAT1    1       210000. .3      7.85-9
MAT1    2       70000.  .33     2.7-9
"""

#: Nastran 자유 필드. 쉼표로 가른다.
NASTRAN_FREE = "MAT1,1,210000.,0.3,7.85E-9\n"

#: LS-DYNA. 열 이름을 `$#` 주석으로 적고 값은 **고정 10칸 오른쪽 맞춤**이다.
LSDYNA = """*MAT_PIECEWISE_LINEAR_PLASTICITY
$#     mid        ro         e        pr      sigy      etan
         1 7.850E-09 2.100E+05     0.300 2.500E+02     0.000
"""

#: LS-DYNA 곡선. **고정 20칸**.
LSDYNA_CURVE = """*DEFINE_CURVE
$#                a1                  o1
           0.0000000         250.0000000
           0.0200000         300.0000000
           0.0500000         340.0000000
"""

#: ANSYS Mechanical APDL. **명령·물성 이름이 값과 같은 줄에** 있다.
ANSYS = """! steel
MP,EX,1,2.1E5
MP,PRXY,1,0.3
MP,DENS,1,7.85E-9
"""

#: OpenRadioss. 키워드가 `/`, 주석이 `#`, 값은 고정 20칸.
RADIOSS = """/MAT/LAW36/1
steel
#                  E                  NU
        2.100000E+05        3.000000E-01
"""


def _values(text: str) -> list[list[str]]:
    """값 줄들의 칸만. 칸 수가 맞는지가 이 시험의 절반이다."""
    return [[cell.text for cell in one.cells] for one in scan.scan(text).lines if one.cells]


def _only(text: str) -> scan.ScannedLine:
    return next(one for one in scan.scan(text).lines if one.cells)


class TestAbaqus:
    def test_키워드와_표가_갈린다(self) -> None:
        found = scan.scan(ABAQUS)
        kinds = [one.kind for one in found.lines]
        assert kinds.count("rows") == 1, kinds
        assert kinds.count("text") == 4

    def test_소수점만_붙은_표기를_읽는다(self) -> None:
        # `210000.` · `0.` — Abaqus 덱에 흔하다. 통째로 한 값이어야 한다.
        assert _values(ABAQUS)[0] == ["210000.", "0.3"]

    def test_밀도_줄의_쉼표를_지킨다(self) -> None:
        density = [one for one in scan.scan(ABAQUS).lines if len(one.cells) == 1]
        assert density and density[0].suffix == ","

    def test_hypermesh_머리를_넘기고_온도표를_읽는다(self) -> None:
        found = scan.scan(HM_ABAQUS)
        # 버전 번호 2021 이 값이 되면 안 된다.
        assert not found.lines[1].cells
        table = [one for one in found.lines if one.kind == "rows"]
        assert len(table) == 1 and table[0].rows == 3
        assert len(table[0].cells) == 3, "온도까지 세 칸이어야 합니다"


class TestNastran:
    def test_생략된_지수를_편다(self) -> None:
        """**`7.85-9` 는 `7.85e-9` 다.** 두 개로 읽으면 칸이 하나 늘고, 그러면
        그 덱은 모든 값이 한 칸씩 밀린다."""
        rows = _values(NASTRAN)
        assert rows[0] == ["1", "210000.", ".3", "7.85-9"]
        cells = _only(NASTRAN).cells
        assert cells[-1].value == 7.85e-9

    def test_왼쪽_맞춤_8칸을_잰다(self) -> None:
        # `MAT1` 이 첫 칸을 차지한다 — 줄 길이를 칸 수로 나누는 방식으로는 못 잰다.
        assert _only(NASTRAN).width == 8

    def test_키워드를_접두로_담는다(self) -> None:
        """**못 담으면 이 솔버는 아예 정의로 못 붙인다.** 공백까지 그대로 둔다 —
        고정폭에서는 그 공백이 칸을 채우는 몫이다."""
        assert _only(NASTRAN).prefix == "MAT1    "

    def test_같은_카드_둘은_표가_아니다(self) -> None:
        # `MAT1 1` 과 `MAT1 2` 는 **다른 재료**다. 둘뿐이라 표로 안 묶인다.
        assert [one.kind for one in scan.scan(NASTRAN).lines if one.cells] == [
            "fields",
            "fields",
        ]

    def test_자유_필드도_읽는다(self) -> None:
        assert _values(NASTRAN_FREE)[0] == ["1", "210000.", "0.3", "7.85E-9"]
        assert _only(NASTRAN_FREE).prefix == "MAT1,"
        # 쉼표로 가르면 고정폭이 아니다.
        assert _only(NASTRAN_FREE).width is None


class TestLsDyna:
    def test_열이름_주석을_값으로_안_읽는다(self) -> None:
        assert [one.kind for one in scan.scan(LSDYNA).lines] == ["text", "text", "fields"]

    def test_오른쪽_맞춤_10칸을_잰다(self) -> None:
        assert _only(LSDYNA).width == 10

    def test_앞_공백을_접두로_안_담는다(self) -> None:
        """**고정폭에서 앞 공백은 첫 칸의 패딩이다.** 접두로 담으면 패딩이 두 번
        들어가 줄 전체가 밀린다."""
        assert _only(LSDYNA).prefix == ""

    def test_여섯_칸을_다_읽는다(self) -> None:
        assert len(_only(LSDYNA).cells) == 6

    def test_곡선은_20칸_표다(self) -> None:
        found = scan.scan(LSDYNA_CURVE)
        table = next(one for one in found.lines if one.kind == "rows")
        assert table.rows == 3
        assert table.width == 20
        assert table.prefix == ""


class TestAnsys:
    def test_세_물성이_한_표로_묶이지_않는다(self) -> None:
        """**여기가 가장 조용히 틀렸다.** `MP,EX`·`MP,PRXY`·`MP,DENS` 는 숫자
        개수가 같아 표로 묶였고, 표는 줄 정의 하나로 여러 줄을 내므로 **두 물성이
        통째로 사라졌다.** 접두 글자가 다르면 다른 줄이다."""
        kinds = [one.kind for one in scan.scan(ANSYS).lines if one.cells]
        assert kinds == ["fields", "fields", "fields"], kinds

    def test_명령을_접두로_담는다(self) -> None:
        prefixes = [one.prefix for one in scan.scan(ANSYS).lines if one.cells]
        assert prefixes == ["MP,EX,", "MP,PRXY,", "MP,DENS,"]

    def test_느낌표_주석을_넘긴다(self) -> None:
        assert scan.scan(ANSYS).lines[0].kind == "text"

    def test_재료_번호와_값을_함께_읽는다(self) -> None:
        assert _values(ANSYS)[0] == ["1", "2.1E5"]


class TestRadioss:
    def test_키워드와_이름_줄을_넘긴다(self) -> None:
        found = scan.scan(RADIOSS)
        assert [one.kind for one in found.lines[:3]] == ["text", "text", "text"]
        # `/MAT/LAW36/1` 의 36·1 이 값이 되면 안 된다.
        assert not found.lines[0].cells

    def test_20칸을_잰다(self) -> None:
        assert _only(RADIOSS).width == 20


class Test모든_덱_공통:
    def test_어느_덱에서도_값_줄을_잃지_않는다(self) -> None:
        """**줄이 사라지는 것이 가장 나쁘다.** 잘못 읽은 칸은 화면에 보이지만,
        없어진 줄은 어디에도 안 보인다."""
        decks = {
            "abaqus": (ABAQUS, 5),
            "hm_abaqus": (HM_ABAQUS, 3),
            "nastran": (NASTRAN, 2),
            "lsdyna": (LSDYNA, 1),
            "lsdyna_curve": (LSDYNA_CURVE, 3),
            "ansys": (ANSYS, 3),
            "radioss": (RADIOSS, 1),
        }
        for name, (text, expected) in decks.items():
            found = scan.scan(text)
            covered = sum(max(one.rows, 1) for one in found.lines if one.cells)
            assert covered == expected, f"{name}: {expected}줄이어야 하는데 {covered}줄"


class Test읽고_다시_낸다:
    """**남의 덱을 읽어 정의로 만들고, 그 정의가 같은 모양의 덱을 내는가.**

    이것이 서면 「배포 없이 새 솔버」 가 말뿐이 아니게 된다 — 읽기만 되고 그 모양
    으로 못 내면 초안은 종이일 뿐이다.
    """

    def test_nastran_왕복(self) -> None:
        from matcore import export
        from matcore.export import template

        found = scan.scan(NASTRAN.splitlines()[1] + "\n")
        line = found.lines[0]
        assert (line.width, line.align) == (8, "left")

        fmt = ["fixed_left" if line.align == "left" else "fixed", line.width, 1]
        spec = {
            "lines": [
                {
                    "prefix": line.prefix,
                    "join": "",
                    "fields": [
                        # **값 줄의 상수.** 재료 번호는 카드에서 오지 않는다.
                        {"const": "1       "},
                        {"value": "elastic.youngs_modulus", "format": fmt},
                        {"value": "elastic.poisson_ratio", "format": fmt},
                        {"value": "elastic.density", "format": fmt},
                    ],
                }
            ]
        }
        deck = export.Deck(
            name="STEEL",
            solver_id=1,
            blocks={
                "elastic": {
                    "values": {
                        "youngs_modulus": 210000.0,
                        "poisson_ratio": 0.3,
                        "density": 7.85e-9,
                    }
                }
            },
            provenance=(),
        )
        made = template.render(spec, deck).text

        back = scan.scan(made).lines[0]
        assert back.prefix == "MAT1    "
        assert (back.width, back.align) == (8, "left"), "낸 덱을 다시 8칸으로 못 읽습니다"
        assert len(back.cells) == 4

    def test_왼쪽_맞춤_형식이_있다(self) -> None:
        """**오른쪽 맞춤만 두면 Nastran·OptiStruct 덱을 낼 수 없다.** 폭만 맞고
        값이 반대쪽에 붙으면 이웃 필드와 붙어 솔버가 둘을 한 값으로 읽는다."""
        from matcore.export import template

        assert "fixed_left" in template.FORMATS
        assert template.FORMATS["fixed_left"](210000.0, (8, 1)) == "2.1E+05 "
        assert template.FORMATS["fixed"](210000.0, (8, 1)) == " 2.1E+05"


#: Nastran 자유 필드에서 **비운 칸**. 네 번째가 전단탄성계수 자리인데, 비우면
#: 「기본값을 쓰라」 는 뜻이다.
NASTRAN_EMPTY = "MAT1,1,210000.,,0.3,7.85E-9\n"

#: 연속 카드. 한 논리 줄이 여러 물리 줄로 나뉜다.
NASTRAN_CONT = """TABLES1        2
+       0.0     250.0    0.01     300.0
+      0.05     340.0    0.10     360.0
+      0.15     370.0    0.20     375.0
"""


class Test비운_칸:
    """**빈 칸을 빼고 세면 뒤 값이 한 칸씩 당겨진다.**

    `MAT1,1,210000.,,0.3,7.85E-9` 의 네 번째는 전단탄성계수 자리다. 그것을 빼고
    세면 `0.3`(푸아송비)이 그 자리로 가고 밀도가 푸아송비 자리로 간다 — 해석은
    그대로 돌고, 솔버는 아무 말도 하지 않는다.
    """

    def test_자리를_지킨다(self) -> None:
        cells = _only(NASTRAN_EMPTY).cells
        assert [cell.text for cell in cells] == ["1", "210000.", "", "0.3", "7.85E-9"]
        assert [cell.empty for cell in cells] == [False, False, True, False, False]

    def test_빈_칸에는_이름을_안_붙인다(self) -> None:
        # 0 으로 읽어 「0 인 값」 을 제안하면 비워 둔 자리가 값으로 채워진다.
        #
        # **막는 겹이 둘이다** — `_suggest` 가 0 인 값을 애초에 제안하지 않고,
        # 빈 칸은 그와 별개로 제안을 건너뛴다. 그래서 한쪽만 망가뜨리면 이 시험은
        # 통과한다(2026-08-30 확인). 겹이 둘인 것 자체는 그대로 둔다 — 빈 칸의
        # 값을 0 으로 두는 한 앞 겹이 우연히 지켜 주는 것이고, 그 우연에 기대지
        # 않는 것이 뒤 겹이다.
        found = scan.scan(NASTRAN_EMPTY, {"elastic.zero": 0.0})
        assert all(cell.suggested is None for cell in found.lines[0].cells if cell.empty)

    def test_줄_끝_쉼표는_칸이_아니다(self) -> None:
        # `*DENSITY` 다음 줄이 `7.85E-09,` 다 — 꼬리지 빈 칸이 아니다.
        line = _only("7.85E-09,\n")
        assert len(line.cells) == 1
        assert line.suffix == ","


class Test연속_카드:
    """`+` 로 이어지는 줄. **접두로 잡히므로 표로 묶인다** — 한계라고 적었던 것이
    실은 이미 되고 있었다(2026-08-30 확인)."""

    def test_연속_줄이_표가_된다(self) -> None:
        found = scan.scan(NASTRAN_CONT)
        table = next(one for one in found.lines if one.kind == "rows")
        assert table.rows == 3
        assert table.prefix == "+       "
        assert len(table.cells) == 4

    def test_머리_줄의_폭을_짐작하지_않는다(self) -> None:
        """`TABLES1        2` 를 16칸으로 쟀었다. 실제로는 8칸 둘이고 앞칸이
        키워드다 — **값 하나로는 알 수 없고, 틀린 폭보다 자유 형식이 안전하다.**"""
        head = next(one for one in scan.scan(NASTRAN_CONT).lines if one.cells)
        assert head.width is None
