"""계산식 표 — 화면에서 적은 식이 적합식·처리 단계가 된다 (ADR 0030)

Revision ID: 000ce19f07d7
Revises: 6e746a0bfd2b
Create Date: 2026-09-13 00:44:35.177865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "000ce19f07d7"
down_revision: Union[str, Sequence[str], None] = "6e746a0bfd2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "formulas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("expression", sa.Text(), nullable=False),
        sa.Column("describe", sa.Text(), nullable=True),
        sa.Column(
            "variables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("x_column", sa.String(length=60), nullable=True),
        sa.Column("y_column", sa.String(length=60), nullable=True),
        sa.Column("block", sa.String(length=40), nullable=True),
        sa.Column(
            "applies_to",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_formulas_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_formulas")),
    )
    op.create_index(op.f("ix_formulas_key"), "formulas", ["key"], unique=True)
    op.create_index(op.f("ix_formulas_kind"), "formulas", ["kind"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_formulas_kind"), table_name="formulas")
    op.drop_index(op.f("ix_formulas_key"), table_name="formulas")
    op.drop_table("formulas")
    # ### end Alembic commands ###
