"""재료의 선언 물성

Revision ID: 02306966487a
Revises: b3cecec7f07c
Create Date: 2026-08-25 02:08:18.804838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "02306966487a"
down_revision: Union[str, Sequence[str], None] = "b3cecec7f07c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "materials",
        sa.Column(
            "declared_properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("materials", "declared_properties")
    # ### end Alembic commands ###
