"""형식 프로파일

Revision ID: 16e6d2d1f6a5
Revises: 74b66487a02e
Create Date: 2026-08-15 21:53:28.506580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "16e6d2d1f6a5"
down_revision: Union[str, Sequence[str], None] = "74b66487a02e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "format_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("test_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "definition",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_format_profiles_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["test_type_id"],
            ["test_types.id"],
            name=op.f("fk_format_profiles_test_type_id_test_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_format_profiles")),
    )
    op.create_index(
        op.f("ix_format_profiles_created_by_id"),
        "format_profiles",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(op.f("ix_format_profiles_key"), "format_profiles", ["key"], unique=True)
    op.create_index(
        op.f("ix_format_profiles_test_type_id"),
        "format_profiles",
        ["test_type_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_format_profiles_test_type_id"), table_name="format_profiles")
    op.drop_index(op.f("ix_format_profiles_key"), table_name="format_profiles")
    op.drop_index(op.f("ix_format_profiles_created_by_id"), table_name="format_profiles")
    op.drop_table("format_profiles")
    # ### end Alembic commands ###
