"""재료 시료 시편과 시험 종류 정의 곡선

Revision ID: 1b3c5c66bc47
Revises: 894e17a97468
Create Date: 2026-08-15 10:11:49.245788

`materials` 의 유니크 제약에 `postgresql_nulls_not_distinct=True` 가 붙어 있다.
`owner_workspace_id IS NULL` 이 전역 재료를 뜻하는데, Postgres 는 기본적으로
NULL 끼리를 중복으로 보지 않는다. 그대로 두면 **전역 재료끼리 같은 이름이
허용되어** 제약을 두는 이유가 사라진다. PG15+ 기능이고 서버는 17.5 다.

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b3c5c66bc47"
down_revision: Union[str, Sequence[str], None] = "894e17a97468"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("abbr", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parser_key", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_types")),
    )
    op.create_index(op.f("ix_test_types_key"), "test_types", ["key"], unique=True)
    op.create_table(
        "test_channels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("test_type_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("dimension", sa.String(length=20), nullable=False),
        sa.Column("si_unit", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["test_type_id"],
            ["test_types.id"],
            name=op.f("fk_test_channels_test_type_id_test_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_channels")),
        sa.UniqueConstraint("test_type_id", "key", name="uq_test_channels_type_key"),
    )
    op.create_index(
        op.f("ix_test_channels_test_type_id"), "test_channels", ["test_type_id"], unique=False
    )
    op.create_table(
        "test_condition_fields",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("test_type_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("value_type", sa.String(length=20), nullable=False),
        sa.Column("dimension", sa.String(length=20), nullable=True),
        sa.Column("si_unit", sa.String(length=20), nullable=True),
        sa.Column("choices", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["test_type_id"],
            ["test_types.id"],
            name=op.f("fk_test_condition_fields_test_type_id_test_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_condition_fields")),
        sa.UniqueConstraint("test_type_id", "key", name="uq_test_condition_fields_type_key"),
    )
    op.create_index(
        op.f("ix_test_condition_fields_test_type_id"),
        "test_condition_fields",
        ["test_type_id"],
        unique=False,
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_workspace_id", sa.UUID(), nullable=True),
        sa.Column("record_name", sa.String(length=200), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=True),
        sa.Column("family", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("grade", sa.String(length=100), nullable=False),
        sa.Column("details", sa.String(length=100), nullable=True),
        sa.Column("spec_thickness_m", sa.Float(), nullable=True),
        sa.Column(
            "input_units",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("legacy_id", sa.String(length=200), nullable=True),
        sa.Column("registered_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_materials_owner_workspace_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["registered_by_id"],
            ["users.id"],
            name=op.f("fk_materials_registered_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint(
            "owner_workspace_id",
            "record_name",
            name="uq_materials_scope_record_name",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(op.f("ix_materials_deleted_at"), "materials", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_materials_legacy_id"), "materials", ["legacy_id"], unique=False)
    op.create_index(
        op.f("ix_materials_owner_workspace_id"),
        "materials",
        ["owner_workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_materials_record_name"), "materials", ["record_name"], unique=False
    )
    op.create_index(
        op.f("ix_materials_registered_by_id"), "materials", ["registered_by_id"], unique=False
    )
    op.create_table(
        "samples",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("seq_no", sa.Integer(), nullable=False),
        sa.Column("record_name", sa.String(length=300), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=True),
        sa.Column("lot_no", sa.String(length=100), nullable=True),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("distributor", sa.String(length=100), nullable=True),
        sa.Column("primary_vendor", sa.String(length=100), nullable=True),
        sa.Column("sales_type", sa.String(length=50), nullable=True),
        sa.Column("applied_product", sa.String(length=100), nullable=True),
        sa.Column("applied_part", sa.String(length=100), nullable=True),
        sa.Column("production_date", sa.Date(), nullable=True),
        sa.Column("density_si", sa.Float(), nullable=True),
        sa.Column("poisson_ratio", sa.Float(), nullable=True),
        sa.Column(
            "input_units",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("legacy_id", sa.String(length=200), nullable=True),
        sa.Column("registered_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], name=op.f("fk_samples_material_id_materials")
        ),
        sa.ForeignKeyConstraint(
            ["registered_by_id"], ["users.id"], name=op.f("fk_samples_registered_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_samples_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_samples")),
        sa.UniqueConstraint("material_id", "seq_no", name="uq_samples_material_seq_no"),
    )
    op.create_index(op.f("ix_samples_deleted_at"), "samples", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_samples_legacy_id"), "samples", ["legacy_id"], unique=False)
    op.create_index(op.f("ix_samples_lot_no"), "samples", ["lot_no"], unique=False)
    op.create_index(op.f("ix_samples_material_id"), "samples", ["material_id"], unique=False)
    op.create_index(op.f("ix_samples_record_name"), "samples", ["record_name"], unique=False)
    op.create_index(
        op.f("ix_samples_registered_by_id"), "samples", ["registered_by_id"], unique=False
    )
    op.create_index(op.f("ix_samples_workspace_id"), "samples", ["workspace_id"], unique=False)
    op.create_table(
        "specimens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("sample_id", sa.UUID(), nullable=False),
        sa.Column("seq_no", sa.Integer(), nullable=False),
        sa.Column("orientation", sa.String(length=10), nullable=False),
        sa.Column("record_name", sa.String(length=300), nullable=False),
        sa.Column("thickness_m", sa.Float(), nullable=True),
        sa.Column("width_m", sa.Float(), nullable=True),
        sa.Column("gauge_length_m", sa.Float(), nullable=True),
        sa.Column(
            "input_units",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("registered_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["registered_by_id"],
            ["users.id"],
            name=op.f("fk_specimens_registered_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"], ["samples.id"], name=op.f("fk_specimens_sample_id_samples")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_specimens_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specimens")),
        sa.UniqueConstraint(
            "sample_id", "orientation", "seq_no", name="uq_specimens_sample_dir_seq_no"
        ),
    )
    op.create_index(op.f("ix_specimens_deleted_at"), "specimens", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_specimens_orientation"), "specimens", ["orientation"], unique=False
    )
    op.create_index(
        op.f("ix_specimens_record_name"), "specimens", ["record_name"], unique=False
    )
    op.create_index(
        op.f("ix_specimens_registered_by_id"), "specimens", ["registered_by_id"], unique=False
    )
    op.create_index(op.f("ix_specimens_sample_id"), "specimens", ["sample_id"], unique=False)
    op.create_index(
        op.f("ix_specimens_workspace_id"), "specimens", ["workspace_id"], unique=False
    )
    op.create_table(
        "test_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("specimen_id", sa.UUID(), nullable=False),
        sa.Column("test_type_id", sa.UUID(), nullable=False),
        sa.Column("seq_no", sa.Integer(), nullable=False),
        sa.Column("record_name", sa.String(length=400), nullable=False),
        sa.Column(
            "conditions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "input_units",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("operator", sa.String(length=100), nullable=True),
        sa.Column("instrument", sa.String(length=100), nullable=True),
        sa.Column("source_filename", sa.String(length=255), nullable=True),
        sa.Column("source_path", sa.String(length=500), nullable=True),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("source_bytes", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="uploaded", nullable=False),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("legacy_id", sa.String(length=200), nullable=True),
        sa.Column("registered_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["registered_by_id"],
            ["users.id"],
            name=op.f("fk_test_runs_registered_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["specimen_id"], ["specimens.id"], name=op.f("fk_test_runs_specimen_id_specimens")
        ),
        sa.ForeignKeyConstraint(
            ["test_type_id"],
            ["test_types.id"],
            name=op.f("fk_test_runs_test_type_id_test_types"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_test_runs_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_runs")),
        sa.UniqueConstraint(
            "specimen_id", "test_type_id", "seq_no", name="uq_test_runs_specimen_type_seq"
        ),
    )
    op.create_index(op.f("ix_test_runs_deleted_at"), "test_runs", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_test_runs_legacy_id"), "test_runs", ["legacy_id"], unique=False)
    op.create_index(
        op.f("ix_test_runs_record_name"), "test_runs", ["record_name"], unique=False
    )
    op.create_index(
        op.f("ix_test_runs_registered_by_id"), "test_runs", ["registered_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_test_runs_source_sha256"), "test_runs", ["source_sha256"], unique=False
    )
    op.create_index(
        op.f("ix_test_runs_specimen_id"), "test_runs", ["specimen_id"], unique=False
    )
    op.create_index(op.f("ix_test_runs_status"), "test_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_test_runs_test_type_id"), "test_runs", ["test_type_id"], unique=False
    )
    op.create_index(op.f("ix_test_runs_tested_at"), "test_runs", ["tested_at"], unique=False)
    op.create_index(
        op.f("ix_test_runs_workspace_id"), "test_runs", ["workspace_id"], unique=False
    )
    op.create_table(
        "curves",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("test_run_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column(
            "channels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"], ["test_runs.id"], name=op.f("fk_curves_test_run_id_test_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curves")),
        sa.UniqueConstraint("test_run_id", "key", name="uq_curves_run_key"),
    )
    op.create_index(op.f("ix_curves_sha256"), "curves", ["sha256"], unique=False)
    op.create_index(op.f("ix_curves_test_run_id"), "curves", ["test_run_id"], unique=False)
    op.create_table(
        "test_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("test_run_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("value_num", sa.Float(), nullable=True),
        sa.Column("value_text", sa.String(length=200), nullable=True),
        sa.Column("si_unit", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_runs.id"],
            name=op.f("fk_test_summaries_test_run_id_test_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_summaries")),
        sa.UniqueConstraint("test_run_id", "key", "source", name="uq_test_summaries_run_key"),
    )
    op.create_index(
        op.f("ix_test_summaries_test_run_id"), "test_summaries", ["test_run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_summaries_test_run_id"), table_name="test_summaries")
    op.drop_table("test_summaries")
    op.drop_index(op.f("ix_curves_test_run_id"), table_name="curves")
    op.drop_index(op.f("ix_curves_sha256"), table_name="curves")
    op.drop_table("curves")
    op.drop_index(op.f("ix_test_runs_workspace_id"), table_name="test_runs")
    op.drop_index(op.f("ix_test_runs_tested_at"), table_name="test_runs")
    op.drop_index(op.f("ix_test_runs_test_type_id"), table_name="test_runs")
    op.drop_index(op.f("ix_test_runs_status"), table_name="test_runs")
    op.drop_index(op.f("ix_test_runs_specimen_id"), table_name="test_runs")
    op.drop_index(op.f("ix_test_runs_source_sha256"), table_name="test_runs")
    op.drop_index(op.f("ix_test_runs_registered_by_id"), table_name="test_runs")
    op.drop_index(op.f("ix_test_runs_record_name"), table_name="test_runs")
    op.drop_index(op.f("ix_test_runs_legacy_id"), table_name="test_runs")
    op.drop_index(op.f("ix_test_runs_deleted_at"), table_name="test_runs")
    op.drop_table("test_runs")
    op.drop_index(op.f("ix_specimens_workspace_id"), table_name="specimens")
    op.drop_index(op.f("ix_specimens_sample_id"), table_name="specimens")
    op.drop_index(op.f("ix_specimens_registered_by_id"), table_name="specimens")
    op.drop_index(op.f("ix_specimens_record_name"), table_name="specimens")
    op.drop_index(op.f("ix_specimens_orientation"), table_name="specimens")
    op.drop_index(op.f("ix_specimens_deleted_at"), table_name="specimens")
    op.drop_table("specimens")
    op.drop_index(op.f("ix_samples_workspace_id"), table_name="samples")
    op.drop_index(op.f("ix_samples_registered_by_id"), table_name="samples")
    op.drop_index(op.f("ix_samples_record_name"), table_name="samples")
    op.drop_index(op.f("ix_samples_material_id"), table_name="samples")
    op.drop_index(op.f("ix_samples_lot_no"), table_name="samples")
    op.drop_index(op.f("ix_samples_legacy_id"), table_name="samples")
    op.drop_index(op.f("ix_samples_deleted_at"), table_name="samples")
    op.drop_table("samples")
    op.drop_index(op.f("ix_materials_registered_by_id"), table_name="materials")
    op.drop_index(op.f("ix_materials_record_name"), table_name="materials")
    op.drop_index(op.f("ix_materials_owner_workspace_id"), table_name="materials")
    op.drop_index(op.f("ix_materials_legacy_id"), table_name="materials")
    op.drop_index(op.f("ix_materials_deleted_at"), table_name="materials")
    op.drop_table("materials")
    op.drop_index(
        op.f("ix_test_condition_fields_test_type_id"), table_name="test_condition_fields"
    )
    op.drop_table("test_condition_fields")
    op.drop_index(op.f("ix_test_channels_test_type_id"), table_name="test_channels")
    op.drop_table("test_channels")
    op.drop_index(op.f("ix_test_types_key"), table_name="test_types")
    op.drop_table("test_types")
    # ### end Alembic commands ###
