"""시험 종류에 소유 부서 — 부서 관리자도 만든다 (ADR 0006)

**기존 행은 전부 전역(NULL)이 된다.** 그게 맞다 — 지금까지는 시스템 관리자만
만들 수 있었으니 전사 자산으로 두고 쓰던 것들이고, 특정 부서에 귀속시키면
다른 부서에서 그 종류가 목록에서 사라진다.

Revision ID: 20b3ac071322
Revises: 7e0ff1906cf0
Create Date: 2026-08-16 17:35:49.181908

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20b3ac071322"
down_revision: Union[str, Sequence[str], None] = "7e0ff1906cf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("test_types", sa.Column("owner_workspace_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_test_types_owner_workspace_id"),
        "test_types",
        ["owner_workspace_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_test_types_owner_workspace_id_workspaces"),
        "test_types",
        "workspaces",
        ["owner_workspace_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_test_types_owner_workspace_id_workspaces"), "test_types", type_="foreignkey"
    )
    op.drop_index(op.f("ix_test_types_owner_workspace_id"), table_name="test_types")
    op.drop_column("test_types", "owner_workspace_id")
    # ### end Alembic commands ###
