"""보유 장비 - 개체·부속·교정 이력

Revision ID: 28ff5e37afe1
Revises: c7a4e0b93f16
Create Date: 2026-09-07 21:36:27.856879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "28ff5e37afe1"
down_revision: Union[str, Sequence[str], None] = "c7a4e0b93f16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment_units",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("asset_no", sa.String(length=80), nullable=True),
        sa.Column("asset_key", sa.String(length=80), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=True),
        sa.Column("instrument_term_id", sa.UUID(), nullable=True),
        sa.Column("type_term_id", sa.UUID(), nullable=True),
        sa.Column("vendor", sa.String(length=200), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("serial_no", sa.String(length=120), nullable=True),
        sa.Column("lab_term_id", sa.UUID(), nullable=True),
        sa.Column("location_detail", sa.String(length=200), nullable=True),
        sa.Column("ownership", sa.String(length=20), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("owner_name", sa.String(length=120), nullable=True),
        sa.Column("owner_contact", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("commissioned_on", sa.Date(), nullable=True),
        sa.Column("retired_on", sa.Date(), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_equipment_units_instrument_id_instruments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_term_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_equipment_units_instrument_term_id_vocabulary_terms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lab_term_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_equipment_units_lab_term_id_vocabulary_terms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["type_term_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_equipment_units_type_term_id_vocabulary_terms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_equipment_units_workspace_id_workspaces"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_units")),
        sa.UniqueConstraint("asset_key", name="uq_equipment_units_asset_key"),
    )
    op.create_index(
        op.f("ix_equipment_units_asset_key"), "equipment_units", ["asset_key"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_units_instrument_id"),
        "equipment_units",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_units_instrument_term_id"),
        "equipment_units",
        ["instrument_term_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_units_lab_term_id"),
        "equipment_units",
        ["lab_term_id"],
        unique=False,
    )
    op.create_index("ix_equipment_units_name", "equipment_units", ["name"], unique=False)
    op.create_index(
        op.f("ix_equipment_units_status"), "equipment_units", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_units_ownership"), "equipment_units", ["ownership"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_units_type_term_id"),
        "equipment_units",
        ["type_term_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_units_workspace_id"),
        "equipment_units",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "equipment_parts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("asset_no", sa.String(length=80), nullable=True),
        sa.Column("vendor", sa.String(length=200), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("serial_no", sa.String(length=120), nullable=True),
        sa.Column("capacity", sa.String(length=120), nullable=True),
        sa.Column("installed_on", sa.Date(), nullable=True),
        sa.Column("removed_on", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["equipment_units.id"],
            name=op.f("fk_equipment_parts_unit_id_equipment_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_parts")),
    )
    op.create_index(op.f("ix_equipment_parts_kind"), "equipment_parts", ["kind"], unique=False)
    op.create_index(
        op.f("ix_equipment_parts_unit_id"), "equipment_parts", ["unit_id"], unique=False
    )
    op.create_table(
        "equipment_calibrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("part_id", sa.UUID(), nullable=True),
        sa.Column("performed_on", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("agency", sa.String(length=200), nullable=True),
        sa.Column("certificate_no", sa.String(length=120), nullable=True),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["equipment_parts.id"],
            name=op.f("fk_equipment_calibrations_part_id_equipment_parts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["equipment_units.id"],
            name=op.f("fk_equipment_calibrations_unit_id_equipment_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_calibrations")),
    )
    op.create_index(
        op.f("ix_equipment_calibrations_part_id"),
        "equipment_calibrations",
        ["part_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_calibrations_performed_on"),
        "equipment_calibrations",
        ["performed_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_calibrations_unit_id"),
        "equipment_calibrations",
        ["unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_calibrations_valid_until"),
        "equipment_calibrations",
        ["valid_until"],
        unique=False,
    )
    # ### end Alembic commands ###

    # --- 기준정보 축 셋 -------------------------------------------------------
    #
    # **축은 마이그레이션이 심어야 한다.** `BUILTIN_VOCABULARIES` 를 읽는
    # `ensure_builtin_vocabularies` 는 시험(conftest)에서만 돈다 — 앱 기동도
    # 배포도 부르지 않는다. 그래서 상수만 늘리면 **이미 있는 DB 는 새 축을 영영
    # 못 받는다**(2026-09-06 에 기준정보 물성 항목으로 같은 함정을 밟았다).
    #
    # 멱등이다. 이미 있으면 건드리지 않는다 — 운영에서 라벨을 고쳤을 수 있다.
    bind = op.get_bind()
    for slug, label, order in (
        ("instrument_type", "장비 유형", 48),
        ("lab", "시험실", 52),
    ):
        bind.execute(
            sa.text(
                """
                INSERT INTO vocabularies (id, slug, label, entry_policy, sort_order,
                                          base_fields, created_at)
                VALUES (gen_random_uuid(), :slug, :label, 'open', :order, '[]', now())
                ON CONFLICT (slug) DO NOTHING
                """
            ),
            {"slug": slug, "label": label, "order": order},
        )

    # **「장비」 축이 「장비 유형」 을 부모로 갖는다.** 유형이 `base_fields` 로 그
    # 유형의 장비가 갖는 칸을 정한다 — UTM 에 「승온 속도」 칸이 있으면 안 되고
    # DSC 에 「제어 방식: 변위」 가 있으면 안 되기 때문이다.
    #
    # 이미 들어 있는 장비 값들은 부모가 빈 채로 산다(`parent_term_id` 가 nullable).
    # 유형은 사람이 나중에 채운다 — 여기서 짐작해 채우면 틀린 분류가 박힌다.
    bind.execute(
        sa.text(
            """
            UPDATE vocabularies
               SET parent_slug = 'instrument_type', attribute_source = 'parent'
             WHERE slug = 'instrument' AND parent_slug IS NULL
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_equipment_calibrations_valid_until"), table_name="equipment_calibrations"
    )
    op.drop_index(
        op.f("ix_equipment_calibrations_unit_id"), table_name="equipment_calibrations"
    )
    op.drop_index(
        op.f("ix_equipment_calibrations_performed_on"), table_name="equipment_calibrations"
    )
    op.drop_index(
        op.f("ix_equipment_calibrations_part_id"), table_name="equipment_calibrations"
    )
    op.drop_table("equipment_calibrations")
    op.drop_index(op.f("ix_equipment_parts_unit_id"), table_name="equipment_parts")
    op.drop_index(op.f("ix_equipment_parts_kind"), table_name="equipment_parts")
    op.drop_table("equipment_parts")
    op.drop_index(op.f("ix_equipment_units_workspace_id"), table_name="equipment_units")
    op.drop_index(op.f("ix_equipment_units_type_term_id"), table_name="equipment_units")
    op.drop_index(op.f("ix_equipment_units_status"), table_name="equipment_units")
    op.drop_index("ix_equipment_units_name", table_name="equipment_units")
    op.drop_index(op.f("ix_equipment_units_lab_term_id"), table_name="equipment_units")
    op.drop_index(op.f("ix_equipment_units_instrument_term_id"), table_name="equipment_units")
    op.drop_index(op.f("ix_equipment_units_instrument_id"), table_name="equipment_units")
    op.drop_index(op.f("ix_equipment_units_asset_key"), table_name="equipment_units")
    op.drop_table("equipment_units")
    # ### end Alembic commands ###
