"""property cards

Revision ID: 297cac8eb557
Revises: f8df87e771ca
Create Date: 2026-08-17 12:51:51.181762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '297cac8eb557'
down_revision: Union[str, Sequence[str], None] = 'f8df87e771ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('test_type_id', sa.UUID(), nullable=False),
    sa.Column('orientation', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('ensemble_result_id', sa.UUID(), nullable=True),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('elastic', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('hardening', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('table', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('point_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('published_by_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_property_cards_created_by_id_users')),
    sa.ForeignKeyConstraint(['ensemble_result_id'], ['ensemble_results.id'], name=op.f('fk_property_cards_ensemble_result_id_ensemble_results')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_property_cards_material_id_materials')),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], name=op.f('fk_property_cards_published_by_id_users')),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_types.id'], name=op.f('fk_property_cards_test_type_id_test_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_cards'))
    )
    op.create_index(op.f('ix_property_cards_created_at'), 'property_cards', ['created_at'], unique=False)
    op.create_index(op.f('ix_property_cards_created_by_id'), 'property_cards', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_property_cards_ensemble_result_id'), 'property_cards', ['ensemble_result_id'], unique=False)
    op.create_index(op.f('ix_property_cards_material_id'), 'property_cards', ['material_id'], unique=False)
    op.create_index(op.f('ix_property_cards_orientation'), 'property_cards', ['orientation'], unique=False)
    op.create_index(op.f('ix_property_cards_status'), 'property_cards', ['status'], unique=False)
    op.create_index(op.f('ix_property_cards_test_type_id'), 'property_cards', ['test_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_cards_test_type_id'), table_name='property_cards')
    op.drop_index(op.f('ix_property_cards_status'), table_name='property_cards')
    op.drop_index(op.f('ix_property_cards_orientation'), table_name='property_cards')
    op.drop_index(op.f('ix_property_cards_material_id'), table_name='property_cards')
    op.drop_index(op.f('ix_property_cards_ensemble_result_id'), table_name='property_cards')
    op.drop_index(op.f('ix_property_cards_created_by_id'), table_name='property_cards')
    op.drop_index(op.f('ix_property_cards_created_at'), table_name='property_cards')
    op.drop_table('property_cards')
    # ### end Alembic commands ###
