"""측정 의뢰 — 「이 시료의 이 물성을 재 달라」 가 기록으로 흐르게 (2026-09-14)

의뢰·항목·이력 세 표와 `test_runs.commission_item_id`(시험이 어느 의뢰 항목에 답하는가).

Revision ID: 2dbfbee9014b
Revises: db4c6752ea62
Create Date: 2026-09-14 06:35:26.219052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2dbfbee9014b"
down_revision: Union[str, Sequence[str], None] = "db4c6752ea62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=10), server_default="normal", nullable=False),
        sa.Column("requester_workspace_id", sa.UUID(), nullable=False),
        sa.Column("lab_workspace_id", sa.UUID(), nullable=False),
        sa.Column("sample_id", sa.UUID(), nullable=False),
        sa.Column("sample_plan", sa.Text(), nullable=True),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_commissions_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_commissions_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lab_workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_commissions_lab_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requester_workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_commissions_requester_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["samples.id"],
            name=op.f("fk_commissions_sample_id_samples"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["status_by_id"],
            ["users.id"],
            name=op.f("fk_commissions_status_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commissions")),
        sa.UniqueConstraint("seq", name=op.f("uq_commissions_seq")),
    )
    op.create_index(
        op.f("ix_commissions_created_at"), "commissions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_commissions_lab_workspace_id"),
        "commissions",
        ["lab_workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commissions_requester_workspace_id"),
        "commissions",
        ["requester_workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commissions_sample_id"), "commissions", ["sample_id"], unique=False
    )
    op.create_index(op.f("ix_commissions_status"), "commissions", ["status"], unique=False)
    op.create_table(
        "commission_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("commission_id", sa.UUID(), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("by_id", sa.UUID(), nullable=True),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["by_id"],
            ["users.id"],
            name=op.f("fk_commission_events_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["commission_id"],
            ["commissions.id"],
            name=op.f("fk_commission_events_commission_id_commissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commission_events")),
    )
    op.create_index(op.f("ix_commission_events_at"), "commission_events", ["at"], unique=False)
    op.create_index(
        op.f("ix_commission_events_commission_id"),
        "commission_events",
        ["commission_id"],
        unique=False,
    )
    op.create_table(
        "commission_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("commission_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("test_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "conditions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "input_units",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "orientations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("deliverable", sa.String(length=50), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["commission_id"],
            ["commissions.id"],
            name=op.f("fk_commission_items_commission_id_commissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_type_id"],
            ["test_types.id"],
            name=op.f("fk_commission_items_test_type_id_test_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commission_items")),
    )
    op.create_index(
        op.f("ix_commission_items_commission_id"),
        "commission_items",
        ["commission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commission_items_test_type_id"),
        "commission_items",
        ["test_type_id"],
        unique=False,
    )
    op.add_column("test_runs", sa.Column("commission_item_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_test_runs_commission_item_id"),
        "test_runs",
        ["commission_item_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_test_runs_commission_item_id_commission_items"),
        "test_runs",
        "commission_items",
        ["commission_item_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_test_runs_commission_item_id_commission_items"),
        "test_runs",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_test_runs_commission_item_id"), table_name="test_runs")
    op.drop_column("test_runs", "commission_item_id")
    op.drop_index(op.f("ix_commission_items_test_type_id"), table_name="commission_items")
    op.drop_index(op.f("ix_commission_items_commission_id"), table_name="commission_items")
    op.drop_table("commission_items")
    op.drop_index(op.f("ix_commission_events_commission_id"), table_name="commission_events")
    op.drop_index(op.f("ix_commission_events_at"), table_name="commission_events")
    op.drop_table("commission_events")
    op.drop_index(op.f("ix_commissions_status"), table_name="commissions")
    op.drop_index(op.f("ix_commissions_sample_id"), table_name="commissions")
    op.drop_index(op.f("ix_commissions_requester_workspace_id"), table_name="commissions")
    op.drop_index(op.f("ix_commissions_lab_workspace_id"), table_name="commissions")
    op.drop_index(op.f("ix_commissions_created_at"), table_name="commissions")
    op.drop_table("commissions")
    # ### end Alembic commands ###
