"""커넥터 삭제와 부분 유니크

Revision ID: 32f94428907c
Revises: f69bb89be861
Create Date: 2026-08-29 22:40:42.049746

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32f94428907c"
down_revision: Union[str, Sequence[str], None] = "f69bb89be861"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    **가이드의 trgm 인덱스를 지우는 줄 넷을 또 걷어 냈다.** autogenerate 가 매번
    넣으려 든다 — 모델이 선언하지 않고 마이그레이션에서만 만든 인덱스라 alembic 이
    「없어야 할 것」 으로 본다(`b3e8f1a2c9d4`). 그대로 두면 핸드북 검색이 느려진다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_pipeline_connectors_host"), "pipeline_connectors", type_="unique"
    )
    op.create_index(
        "uq_pipeline_connectors_host",
        "pipeline_connectors",
        ["workspace_id", "hostname"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_pipeline_connectors_deleted_at"),
        "pipeline_connectors",
        ["deleted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_connectors_deleted_at"), table_name="pipeline_connectors")
    op.drop_index(
        "uq_pipeline_connectors_host",
        table_name="pipeline_connectors",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_pipeline_connectors_host"),
        "pipeline_connectors",
        ["workspace_id", "hostname"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
