"""측정 의뢰 — 새 재료·종류 미정 (2026-09-14)

등록 안 된 새 재료(`material_hint`, 시료 없음)와 시험 종류 미정 항목(`property_hint`,
종류 없음)도 의뢰한다. 받는 쪽이 시료를 잇고 종류를 정한 뒤 시험을 붙인다.

Revision ID: 38358a31c0a6
Revises: 2dbfbee9014b
Create Date: 2026-09-14 10:40:07.534633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38358a31c0a6"
down_revision: Union[str, Sequence[str], None] = "2dbfbee9014b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("commission_items", sa.Column("property_hint", sa.Text(), nullable=True))
    op.alter_column("commission_items", "test_type_id", existing_type=sa.UUID(), nullable=True)
    op.add_column("commissions", sa.Column("material_hint", sa.Text(), nullable=True))
    op.alter_column("commissions", "sample_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("commissions", "sample_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("commissions", "material_hint")
    op.alter_column(
        "commission_items", "test_type_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("commission_items", "property_hint")
    # ### end Alembic commands ###
