"""notices and voc

Revision ID: 425c602e06ec
Revises: 8ba4f4b599f7
Create Date: 2026-08-15 02:34:47.107207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "425c602e06ec"
down_revision: Union[str, Sequence[str], None] = "8ba4f4b599f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_popup", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_notices_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notices")),
    )
    op.create_index(op.f("ix_notices_created_at"), "notices", ["created_at"], unique=False)
    op.create_table(
        "voc_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("page_path", sa.String(length=300), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reply", sa.Text(), nullable=True),
        sa.Column("replied_by_id", sa.UUID(), nullable=True),
        sa.Column("replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_voc_items_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["replied_by_id"],
            ["users.id"],
            name=op.f("fk_voc_items_replied_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_voc_items")),
    )
    op.create_index(op.f("ix_voc_items_created_at"), "voc_items", ["created_at"], unique=False)
    op.create_index(op.f("ix_voc_items_status"), "voc_items", ["status"], unique=False)
    op.create_table(
        "notice_reads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("notice_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "read_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notices.id"],
            name=op.f("fk_notice_reads_notice_id_notices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notice_reads_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notice_reads")),
        sa.UniqueConstraint("notice_id", "user_id", name="uq_notice_reads_pair"),
    )
    op.create_index(
        op.f("ix_notice_reads_notice_id"), "notice_reads", ["notice_id"], unique=False
    )
    op.create_index(op.f("ix_notice_reads_user_id"), "notice_reads", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notice_reads_user_id"), table_name="notice_reads")
    op.drop_index(op.f("ix_notice_reads_notice_id"), table_name="notice_reads")
    op.drop_table("notice_reads")
    op.drop_index(op.f("ix_voc_items_status"), table_name="voc_items")
    op.drop_index(op.f("ix_voc_items_created_at"), table_name="voc_items")
    op.drop_table("voc_items")
    op.drop_index(op.f("ix_notices_created_at"), table_name="notices")
    op.drop_table("notices")
    # ### end Alembic commands ###
