"""test_summaries dimension

Revision ID: 4793f2545a1e
Revises: 905af0fd60d6
Create Date: 2026-08-17 08:29:59.865022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4793f2545a1e'
down_revision: Union[str, Sequence[str], None] = '905af0fd60d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_summaries', sa.Column('dimension', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_summaries', 'dimension')
    # ### end Alembic commands ###
