"""어휘 표와 제조사 축

Revision ID: 678637a142ba
Revises: 154c0d5508af
Create Date: 2026-08-20 21:13:30.648055

"""

from typing import Sequence, Union

import logging

from alembic import op
import sqlalchemy as sa

from app.modules.vocabulary.normalize import clean, compare_key

logger = logging.getLogger("alembic.runtime.migration")


# revision identifiers, used by Alembic.
revision: str = "678637a142ba"
down_revision: Union[str, Sequence[str], None] = "154c0d5508af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- 축 심기와 백필 ---------------------------------------------------------
#
# **축은 마이그레이션으로 심는다.** 축이 늘어나는 것은 스키마가 바뀌는 일이지
# 데이터가 늘어나는 일이 아니다 — API 로 만들게 두면 오타 난 축이 생긴다.
#
# 1단계는 제조사 하나만 옮긴다. 모델·마이그레이션·백필·폼·목록·통계 경고를 한
# 번씩 지나므로, 막히는 것이 있으면 나머지 열 축에 반복되기 전에 잡힌다.

VOCABULARIES = [
    # slug, label, entry_policy, sort_order
    ("manufacturer", "제조사", "open", 10),
]


def _seed_and_backfill() -> None:
    bind = op.get_bind()
    for slug, label, policy, order in VOCABULARIES:
        bind.execute(
            sa.text(
                "INSERT INTO vocabularies (id, slug, label, entry_policy, sort_order)"
                " VALUES (gen_random_uuid(), :slug, :label, :policy, :order)"
            ),
            {"slug": slug, "label": label, "policy": policy, "order": order},
        )

    vocabulary_id = bind.execute(
        sa.text("SELECT id FROM vocabularies WHERE slug = 'manufacturer'")
    ).scalar_one()

    # 값 만들기. **비교키로 묶는다** — '포스코' 와 '포스코 ' 는 한 값이다.
    # 정규화는 파이썬에 있으므로(NFKC·제로폭·공백) 여기서 읽어다 쓴다.
    rows = bind.execute(
        sa.text(
            "SELECT id, manufacturer FROM samples"
            " WHERE manufacturer IS NOT NULL AND manufacturer <> ''"
        )
    ).all()

    by_key: dict[str, str] = {}
    merged: list[tuple[str, str]] = []
    for _sample_id, raw in rows:
        key = compare_key(raw)
        if not key:
            continue
        value = clean(raw) or raw
        if key in by_key and by_key[key] != value:
            # 표기가 갈렸다 — 하나로 모으되 **무엇을 무엇으로 모았는지 남긴다.**
            merged.append((value, by_key[key]))
            continue
        by_key.setdefault(key, value)

    for key, value in by_key.items():
        bind.execute(
            sa.text(
                "INSERT INTO vocabulary_terms"
                " (id, vocabulary_id, value, normalized, status, usage_count)"
                " VALUES (gen_random_uuid(), :vid, :value, :key, 'active', 0)"
            ),
            {"vid": vocabulary_id, "value": value, "key": key},
        )
    for dropped, kept in merged:
        logger.info("제조사 표기를 모았습니다: %r → %r", dropped, kept)

    # FK 채우기 + usage_count. 한 문장으로 — 행마다 돌면 5만 건에서 느리다.
    filled = bind.execute(
        sa.text(
            """
            UPDATE samples AS s
               SET manufacturer_term_id = t.id
              FROM vocabulary_terms AS t
             WHERE t.vocabulary_id = :vid
               AND t.normalized = lower(btrim(s.manufacturer))
               AND s.manufacturer IS NOT NULL
            """
        ),
        {"vid": vocabulary_id},
    ).rowcount
    bind.execute(
        sa.text(
            """
            UPDATE vocabulary_terms AS t
               SET usage_count = c.n
              FROM (SELECT manufacturer_term_id AS id, count(*) AS n
                      FROM samples WHERE manufacturer_term_id IS NOT NULL
                     GROUP BY manufacturer_term_id) AS c
             WHERE t.id = c.id
            """
        )
    )
    logger.info("제조사 어휘 %s종 · 시료 %s건 연결", len(by_key), filled)

    # **못 채운 것이 있으면 말한다.** SQL 의 `lower(btrim())` 은 파이썬 정규화보다
    # 약하다(NFKC·제로폭을 모른다). 남은 것은 사람이 봐야 한다.
    leftover = (
        bind.execute(
            sa.text(
                "SELECT DISTINCT manufacturer FROM samples"
                " WHERE manufacturer IS NOT NULL AND manufacturer <> ''"
                "   AND manufacturer_term_id IS NULL"
            )
        )
        .scalars()
        .all()
    )
    for value in leftover:
        logger.warning(
            "제조사 %r 를 어휘로 못 옮겼습니다 — 눈에 안 보이는 문자가 있을 수 "
            "있습니다. 시료 수정에서 다시 고르세요.",
            value,
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vocabularies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("entry_policy", sa.String(length=10), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabularies")),
    )
    op.create_index(op.f("ix_vocabularies_slug"), "vocabularies", ["slug"], unique=True)
    op.create_table(
        "vocabulary_terms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vocabulary_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("normalized", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("usage_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_vocabulary_terms_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["vocabulary_id"],
            ["vocabularies.id"],
            name=op.f("fk_vocabulary_terms_vocabulary_id_vocabularies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabulary_terms")),
        sa.UniqueConstraint("vocabulary_id", "normalized", name="uq_vocabulary_terms_norm"),
    )
    op.create_index(
        "ix_vocabulary_terms_norm_trgm",
        "vocabulary_terms",
        ["normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_vocabulary_terms_normalized"),
        "vocabulary_terms",
        ["normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vocabulary_terms_status"), "vocabulary_terms", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_vocabulary_terms_vocabulary_id"),
        "vocabulary_terms",
        ["vocabulary_id"],
        unique=False,
    )
    op.create_table(
        "vocabulary_aliases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vocabulary_id", sa.UUID(), nullable=False),
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("normalized", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_vocabulary_aliases_term_id_vocabulary_terms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vocabulary_id"],
            ["vocabularies.id"],
            name=op.f("fk_vocabulary_aliases_vocabulary_id_vocabularies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabulary_aliases")),
        sa.UniqueConstraint("vocabulary_id", "normalized", name="uq_vocabulary_aliases_norm"),
    )
    op.create_index(
        "ix_vocabulary_aliases_norm_trgm",
        "vocabulary_aliases",
        ["normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_vocabulary_aliases_normalized"),
        "vocabulary_aliases",
        ["normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vocabulary_aliases_term_id"), "vocabulary_aliases", ["term_id"], unique=False
    )
    op.create_index(
        op.f("ix_vocabulary_aliases_vocabulary_id"),
        "vocabulary_aliases",
        ["vocabulary_id"],
        unique=False,
    )
    op.add_column("samples", sa.Column("manufacturer_term_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_samples_manufacturer_term_id"),
        "samples",
        ["manufacturer_term_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_samples_manufacturer_term_id_vocabulary_terms"),
        "samples",
        "vocabulary_terms",
        ["manufacturer_term_id"],
        ["id"],
    )
    # ### end Alembic commands ###
    _seed_and_backfill()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_samples_manufacturer_term_id_vocabulary_terms"), "samples", type_="foreignkey"
    )
    op.drop_index(op.f("ix_samples_manufacturer_term_id"), table_name="samples")
    op.drop_column("samples", "manufacturer_term_id")
    op.drop_index(op.f("ix_vocabulary_aliases_vocabulary_id"), table_name="vocabulary_aliases")
    op.drop_index(op.f("ix_vocabulary_aliases_term_id"), table_name="vocabulary_aliases")
    op.drop_index(op.f("ix_vocabulary_aliases_normalized"), table_name="vocabulary_aliases")
    op.drop_index(
        "ix_vocabulary_aliases_norm_trgm",
        table_name="vocabulary_aliases",
        postgresql_using="gin",
        postgresql_ops={"normalized": "gin_trgm_ops"},
    )
    op.drop_table("vocabulary_aliases")
    op.drop_index(op.f("ix_vocabulary_terms_vocabulary_id"), table_name="vocabulary_terms")
    op.drop_index(op.f("ix_vocabulary_terms_status"), table_name="vocabulary_terms")
    op.drop_index(op.f("ix_vocabulary_terms_normalized"), table_name="vocabulary_terms")
    op.drop_index(
        "ix_vocabulary_terms_norm_trgm",
        table_name="vocabulary_terms",
        postgresql_using="gin",
        postgresql_ops={"normalized": "gin_trgm_ops"},
    )
    op.drop_table("vocabulary_terms")
    op.drop_index(op.f("ix_vocabularies_slug"), table_name="vocabularies")
    op.drop_table("vocabularies")
    # ### end Alembic commands ###
