"""업로드 한도와 장비 원문 메타

Revision ID: 74b66487a02e
Revises: 1b3c5c66bc47
Create Date: 2026-08-15 15:04:59.810150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "74b66487a02e"
down_revision: Union[str, Sequence[str], None] = "1b3c5c66bc47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_runs",
        sa.Column(
            "source_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "test_runs", sa.Column("parser_version", sa.String(length=20), nullable=True)
    )
    op.add_column("test_types", sa.Column("max_upload_bytes", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_types", "max_upload_bytes")
    op.drop_column("test_runs", "parser_version")
    op.drop_column("test_runs", "source_metadata")
    # ### end Alembic commands ###
