"""어긋남 점검 기록

Revision ID: 7a402bba2eca
Revises: faaa94df2735
Create Date: 2026-08-21 10:34:52.661149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7a402bba2eca"
down_revision: Union[str, Sequence[str], None] = "faaa94df2735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# **`now()` 가 아니라 `clock_timestamp()`.** 포스트그레스의 `now()` 는 트랜잭션
# 시작 시각이라 한 트랜잭션에 넣은 두 줄이 같은 시각을 받는다. 고치기는 한 번에
# 두 줄을 남기므로(고치기 전·후) 그러면 순서가 사라지고 "언제부터 0" 이 틀린다.


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vocabulary_drift_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabulary_drift_checks")),
    )
    op.create_index(
        op.f("ix_vocabulary_drift_checks_checked_at"),
        "vocabulary_drift_checks",
        ["checked_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_vocabulary_drift_checks_checked_at"), table_name="vocabulary_drift_checks"
    )
    op.drop_table("vocabulary_drift_checks")
    # ### end Alembic commands ###
