"""프로파일 부서 소유

Revision ID: 7e0ff1906cf0
Revises: f00ab8469618
Create Date: 2026-08-16 14:32:57.503529

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e0ff1906cf0"
down_revision: Union[str, Sequence[str], None] = "f00ab8469618"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("format_profiles", sa.Column("owner_workspace_id", sa.UUID(), nullable=True))
    op.drop_index(op.f("ix_format_profiles_key"), table_name="format_profiles")
    op.create_index(op.f("ix_format_profiles_key"), "format_profiles", ["key"], unique=False)
    op.create_index(
        op.f("ix_format_profiles_owner_workspace_id"),
        "format_profiles",
        ["owner_workspace_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_format_profiles_scope_key",
        "format_profiles",
        ["owner_workspace_id", "key"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_foreign_key(
        op.f("fk_format_profiles_owner_workspace_id_workspaces"),
        "format_profiles",
        "workspaces",
        ["owner_workspace_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_format_profiles_owner_workspace_id_workspaces"),
        "format_profiles",
        type_="foreignkey",
    )
    op.drop_constraint("uq_format_profiles_scope_key", "format_profiles", type_="unique")
    op.drop_index(op.f("ix_format_profiles_owner_workspace_id"), table_name="format_profiles")
    op.drop_index(op.f("ix_format_profiles_key"), table_name="format_profiles")
    op.create_index(op.f("ix_format_profiles_key"), "format_profiles", ["key"], unique=True)
    op.drop_column("format_profiles", "owner_workspace_id")
    # ### end Alembic commands ###
