"""별칭 병합 기록

Revision ID: 82ac9bab9b5c
Revises: 71f73806a42f
Create Date: 2026-08-21 03:29:12.336261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ac9bab9b5c'
down_revision: Union[str, Sequence[str], None] = '71f73806a42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_dismissals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('low_term_id', sa.UUID(), nullable=False),
    sa.Column('high_term_id', sa.UUID(), nullable=False),
    sa.Column('dismissed_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dismissed_by_id'], ['users.id'], name=op.f('fk_vocabulary_dismissals_dismissed_by_id_users')),
    sa.ForeignKeyConstraint(['high_term_id'], ['vocabulary_terms.id'], name=op.f('fk_vocabulary_dismissals_high_term_id_vocabulary_terms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['low_term_id'], ['vocabulary_terms.id'], name=op.f('fk_vocabulary_dismissals_low_term_id_vocabulary_terms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_dismissals')),
    sa.UniqueConstraint('low_term_id', 'high_term_id', name='uq_vocabulary_dismissals')
    )
    op.create_table('vocabulary_merges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vocabulary_id', sa.UUID(), nullable=False),
    sa.Column('source_value', sa.String(length=200), nullable=False),
    sa.Column('target_term_id', sa.UUID(), nullable=True),
    sa.Column('target_value', sa.String(length=200), nullable=False),
    sa.Column('moved_count', sa.Integer(), nullable=False),
    sa.Column('merged_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_by_id'], ['users.id'], name=op.f('fk_vocabulary_merges_merged_by_id_users')),
    sa.ForeignKeyConstraint(['target_term_id'], ['vocabulary_terms.id'], name=op.f('fk_vocabulary_merges_target_term_id_vocabulary_terms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], name=op.f('fk_vocabulary_merges_vocabulary_id_vocabularies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_merges'))
    )
    op.create_index(op.f('ix_vocabulary_merges_target_term_id'), 'vocabulary_merges', ['target_term_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_merges_vocabulary_id'), 'vocabulary_merges', ['vocabulary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_merges_vocabulary_id'), table_name='vocabulary_merges')
    op.drop_index(op.f('ix_vocabulary_merges_target_term_id'), table_name='vocabulary_merges')
    op.drop_table('vocabulary_merges')
    op.drop_table('vocabulary_dismissals')
    # ### end Alembic commands ###
