"""물성 이름 사전 - 별칭과 매핑

Revision ID: 888bca60a86b
Revises: e913af29ac90
Create Date: 2026-09-08 08:57:19.369102

"""

from typing import Sequence, Union

from alembic import op
import logging

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "888bca60a86b"
down_revision: Union[str, Sequence[str], None] = "e913af29ac90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: 물성별 별칭 씨앗. **검사가 같은 목록을 봐야 하므로** 밖에 둔다 —
#: 아래 INSERT 는 없는 키를 조용히 건너뛴다.
_ALIAS_SEED: tuple[tuple[str, list[tuple[str, str, str | None]]], ...] = (
    (
        "mechanical.yield_strength",
        [
            ("항복응력", "seed", "금속 문맥에서 사람이 흔히 이렇게 부른다"),
            ("항복점", "seed", None),
            ("yield strength", "standard", None),
            ("yield stress", "seed", "금속 문맥. 유변학 항복응력과 다르다"),
            ("proof stress", "standard", "ISO 6892 표기"),
            ("0.2% proof stress", "standard", "ISO 6892-1 Rp0.2"),
            ("Rp0.2", "standard", "ISO 6892-1"),
            ("YS", "seed", None),
        ],
    ),
    (
        "mechanical.tensile_strength",
        [
            ("인장강도", "seed", None),
            ("최대인장강도", "seed", None),
            ("tensile strength", "standard", None),
            ("ultimate tensile strength", "standard", None),
            ("UTS", "seed", None),
            ("Rm", "standard", "ISO 6892-1"),
        ],
    ),
    (
        "mechanical.youngs_modulus",
        [
            ("탄성계수", "seed", None),
            ("영률", "seed", None),
            ("종탄성계수", "seed", None),
            ("Young's modulus", "standard", None),
            ("elastic modulus", "seed", None),
            ("E", "standard", None),
        ],
    ),
    (
        "mechanical.shear_modulus",
        [
            ("전단탄성계수", "seed", None),
            ("shear modulus", "standard", None),
            ("G", "standard", None),
        ],
    ),
    (
        "mechanical.elongation_at_break",
        [
            ("연신율", "seed", None),
            ("파단연신율", "seed", None),
            ("elongation", "seed", None),
            ("elongation at break", "standard", None),
            ("A", "standard", "ISO 6892-1"),
        ],
    ),
    (
        "physical.density",
        [("밀도", "seed", None), ("density", "standard", None), ("rho", "seed", None)],
    ),
    (
        "mechanical.poisson_ratio",
        [
            ("푸아송비", "seed", None),
            ("포아송비", "seed", "표기 흔들림"),
            ("Poisson's ratio", "standard", None),
        ],
    ),
    (
        "thermal.conductivity",
        [
            ("열전도율", "seed", None),
            ("열전도도", "seed", None),
            ("thermal conductivity", "standard", None),
        ],
    ),
    (
        "thermal.specific_heat",
        [
            ("비열", "seed", None),
            ("specific heat", "standard", None),
            ("Cp", "standard", None),
        ],
    ),
    (
        "thermal.expansion_linear",
        [
            ("선팽창계수", "seed", None),
            ("열팽창계수", "seed", None),
            ("CTE", "standard", None),
        ],
    ),
)


logger = logging.getLogger("alembic.runtime.migration")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "property_aliases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("property_key", sa.String(length=120), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("normalized", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_property_aliases_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_aliases")),
        sa.UniqueConstraint("property_key", "normalized", name="uq_property_aliases"),
    )
    op.create_index(
        op.f("ix_property_aliases_normalized"),
        "property_aliases",
        ["normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_aliases_property_key"),
        "property_aliases",
        ["property_key"],
        unique=False,
    )
    op.create_table(
        "property_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("property_key", sa.String(length=120), nullable=False),
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_property_links_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_property_links_term_id_vocabulary_terms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_links")),
        sa.UniqueConstraint("property_key", "term_id", name="uq_property_links"),
    )
    op.create_index(
        op.f("ix_property_links_property_key"),
        "property_links",
        ["property_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_links_term_id"), "property_links", ["term_id"], unique=False
    )
    # ### end Alembic commands ###

    # --- 씨앗: 매핑과 별칭 -----------------------------------------------------
    #
    # **짚은 키가 실재하는지 먼저 본다.** 아래 INSERT 는 `EXISTS` 로 없는 키를
    # 조용히 건너뛰는데(문헌 정의가 아직 안 들어온 새 DB 를 위해서다), 그러면
    # **오타가 있어도 조용하다** — 실측(2026-09-08)에서 넷이 그렇게 빠졌다.
    # 정의가 하나라도 있는 DB 에서만 검사한다.
    #
    # **사내 물성 항목 9개를 문헌 정의에 잇는다.** ADR 0027 이 미뤄 둔 매핑이고,
    # 이것이 없으면 「이 재료의 항복강도」 가 사내와 문헌에서 다른 것을 가리킨다.
    #
    # 문헌 정의가 아직 안 들어온 DB(새 설치)에서는 조용히 건너뛴다 — 이관이 나중에
    # 돌면 그때 관리 화면에서 잇는다. **없는 것을 지어내지 않는다.**
    bind = op.get_bind()
    for item, key in (
        ("항복강도", "mechanical.yield_strength"),
        ("인장강도", "mechanical.tensile_strength"),
        ("탄성계수", "mechanical.youngs_modulus"),
        ("전단탄성계수", "mechanical.shear_modulus"),
        ("연신율", "mechanical.elongation_at_break"),
        ("경도", "mechanical.hardness_vickers"),
        ("열전도율", "thermal.conductivity"),
        ("비열", "thermal.specific_heat"),
        ("선팽창계수(CTE)", "thermal.expansion_linear"),
    ):
        bind.execute(
            sa.text(
                """
                INSERT INTO property_links (id, property_key, term_id, kind, created_at)
                SELECT gen_random_uuid(), CAST(:key AS varchar), t.id, 'same_as', now()
                  FROM vocabulary_terms t
                  JOIN vocabularies v ON v.id = t.vocabulary_id
                 WHERE v.slug = 'property_item' AND t.value = CAST(:item AS varchar)
                   AND EXISTS (SELECT 1 FROM catalog_definitions d WHERE d.key = CAST(:key AS varchar))
                ON CONFLICT DO NOTHING
                """
            ),
            {"item": item, "key": key},
        )

    # **별칭 — 사람이 실제로 부르는 말.**
    #
    # 「항복응력」 을 `mechanical.yield_strength` 에 붙이는 것이 이 씨앗의 핵심이다.
    # 이름이 정확히 「항복응력」 인 정의는 유변학 물성(`rheological.yield_stress`,
    # 9건, 8~20 Pa)이라, 별칭이 없으면 금속을 물었는데 페이스트가 나온다.
    #
    # 규격 표기(Rp0.2 · 0.2% proof stress)는 근거가 있어 `standard` 로, 우리가
    # 흔히 쓰는 말은 `seed` 로 적는다 — 지어낸 것과 근거 있는 것을 구별한다.
    for key, aliases in _ALIAS_SEED:
        for alias, source, note in aliases:
            bind.execute(
                sa.text(
                    """
                    INSERT INTO property_aliases
                           (id, property_key, alias, normalized, source, note, created_at)
                    SELECT gen_random_uuid(), CAST(:key AS varchar), CAST(:alias AS varchar),
                           lower(CAST(:alias AS varchar)), CAST(:source AS varchar),
                           CAST(:note AS text), now()
                     WHERE EXISTS (SELECT 1 FROM catalog_definitions d WHERE d.key = CAST(:key AS varchar))
                    ON CONFLICT DO NOTHING
                    """
                ),
                {"key": key, "alias": alias, "source": source, "note": note},
            )

    # 정의가 들어와 있는데 못 붙인 키가 있으면 로그에 남긴다. 배포를 세우지는
    # 않는다 — 별칭이 비는 것은 불편이지 장애가 아니다.
    if bind.execute(sa.text("SELECT count(*) FROM catalog_definitions")).scalar():
        missed = (
            bind.execute(
                sa.text(
                    """
                SELECT DISTINCT s.key FROM (
                    SELECT unnest(CAST(:keys AS text[])) AS key
                ) AS s
                 WHERE NOT EXISTS (
                       SELECT 1 FROM catalog_definitions d WHERE d.key = s.key)
                """
                ),
                {"keys": sorted({key for key, _ in _ALIAS_SEED})},
            )
            .scalars()
            .all()
        )
        if missed:
            logger.warning("물성 별칭 씨앗이 못 찾은 키: %s", ", ".join(missed))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_property_links_term_id"), table_name="property_links")
    op.drop_index(op.f("ix_property_links_property_key"), table_name="property_links")
    op.drop_table("property_links")
    op.drop_index(op.f("ix_property_aliases_property_key"), table_name="property_aliases")
    op.drop_index(op.f("ix_property_aliases_normalized"), table_name="property_aliases")
    op.drop_table("property_aliases")
    # ### end Alembic commands ###
