"""access logs

Revision ID: 894e17a97468
Revises: 425c602e06ec
Create Date: 2026-08-15 02:41:14.466194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "894e17a97468"
down_revision: Union[str, Sequence[str], None] = "425c602e06ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("path", sa.String(length=300), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=40), nullable=True),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_access_logs_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_logs")),
    )
    op.create_index(op.f("ix_access_logs_action"), "access_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_access_logs_created_at"), "access_logs", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_access_logs_user_id"), "access_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_access_logs_user_id"), table_name="access_logs")
    op.drop_index(op.f("ix_access_logs_created_at"), table_name="access_logs")
    op.drop_index(op.f("ix_access_logs_action"), table_name="access_logs")
    op.drop_table("access_logs")
    # ### end Alembic commands ###
