"""별칭 후보 — 못 푼 물성 이름을 쌓아 관리자가 별칭으로 승인하는 큐(2026-09-16).

Revision ID: 8a95c7e22b4e
Revises: 36f49bf093c7
Create Date: 2026-09-16 19:51:31.716654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a95c7e22b4e"
down_revision: Union[str, Sequence[str], None] = "36f49bf093c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alias_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("text", sa.String(length=200), nullable=False),
        sa.Column("normalized", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resolved_to", sa.String(length=120), nullable=True),
        sa.Column("resolved_by_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
            name=op.f("fk_alias_candidates_resolved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alias_candidates")),
        sa.UniqueConstraint("kind", "normalized", name="uq_alias_candidates_text"),
    )
    op.create_index(
        op.f("ix_alias_candidates_normalized"),
        "alias_candidates",
        ["normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alias_candidates_status"), "alias_candidates", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alias_candidates_status"), table_name="alias_candidates")
    op.drop_index(op.f("ix_alias_candidates_normalized"), table_name="alias_candidates")
    op.drop_table("alias_candidates")
    # ### end Alembic commands ###
