"""워크벤치 작업과 바구니

Revision ID: 8d0e713c5c48
Revises: 29ceaa77f728
Create Date: 2026-09-01 14:25:44.371893

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8d0e713c5c48"
down_revision: Union[str, Sequence[str], None] = "29ceaa77f728"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workbench_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("workflow_key", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="running", nullable=False),
        sa.Column(
            "steps",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_workbench_runs_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workbench_runs_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workbench_runs")),
    )
    op.create_index(
        op.f("ix_workbench_runs_status"), "workbench_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_workbench_runs_workflow_key"),
        "workbench_runs",
        ["workflow_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workbench_runs_workspace_id"),
        "workbench_runs",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_workbench_runs_workspace_status",
        "workbench_runs",
        ["workspace_id", "status"],
        unique=False,
    )
    op.create_table(
        "workbench_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["workbench_runs.id"],
            name=op.f("fk_workbench_items_run_id_workbench_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workbench_items")),
    )
    op.create_index(
        op.f("ix_workbench_items_run_id"), "workbench_items", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_workbench_items_target_id"), "workbench_items", ["target_id"], unique=False
    )
    op.create_index(
        "uq_workbench_items", "workbench_items", ["run_id", "kind", "target_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_workbench_items", table_name="workbench_items")
    op.drop_index(op.f("ix_workbench_items_target_id"), table_name="workbench_items")
    op.drop_index(op.f("ix_workbench_items_run_id"), table_name="workbench_items")
    op.drop_table("workbench_items")
    op.drop_index("ix_workbench_runs_workspace_status", table_name="workbench_runs")
    op.drop_index(op.f("ix_workbench_runs_workspace_id"), table_name="workbench_runs")
    op.drop_index(op.f("ix_workbench_runs_workflow_key"), table_name="workbench_runs")
    op.drop_index(op.f("ix_workbench_runs_status"), table_name="workbench_runs")
    op.drop_table("workbench_runs")
    # ### end Alembic commands ###
