"""시험이 자기 치수를 든다.

실사용에서 나왔다 — *"시편 하나에 여러 시험으로 넣으니까, 그 시험은 다 같은
두께, 폭을 가지게 되어 버린다"*.

치수는 **그 시험에서 잰 값**이다. 장비 파일마다 `a0`·`b0` 가 들어 있는데, 지금은
시편 행 한 곳에만 자리가 있어서 시험 N개가 한 벌을 나눠 쓴다. 두 번째 파일이
들고 온 값은 갈 데가 없다.

**비우고 시작한다.** 이미 들어온 시험의 값을 여기로 옮기지 않는다 — 옮기려면
그 시험이 어느 파일이었는지 다시 읽어야 하고, 그건 원본을 다시 읽으면 되는
일이다(ADR 0005). 비어 있으면 전과 똑같이 시편 값을 쓴다.

Revision ID: 985f5610be6e
Revises: f1c62a4d8b09
Create Date: 2026-08-27 19:06:33.129007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '985f5610be6e'
down_revision: Union[str, Sequence[str], None] = 'f1c62a4d8b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'dimensions')
    # ### end Alembic commands ###
