"""parser_version 폭

Revision ID: a06c3890ff83
Revises: b2c21627d4f6
Create Date: 2026-08-16 10:51:54.519444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a06c3890ff83"
down_revision: Union[str, Sequence[str], None] = "b2c21627d4f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "test_runs",
        "parser_version",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=80),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "test_runs",
        "parser_version",
        existing_type=sa.String(length=80),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
