"""정의를 통째로 갈아 끼울 때 덮어쓰기를 막는다

Revision ID: a37bf9bc1de3
Revises: d4b8c2f61a09
Create Date: 2026-08-24 18:10:15.786622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a37bf9bc1de3"
down_revision: Union[str, Sequence[str], None] = "d4b8c2f61a09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processing_recipes",
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "test_types", sa.Column("revision", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_types", "revision")
    op.drop_column("processing_recipes", "revision")
    # ### end Alembic commands ###
