"""시편 분류가 기본 칸을 갖는다

## 왜 갈아엎는가

바로 앞 리비전(`fda81ee7706e`)은 치수 칸을 **시험 종류**에 매달았다. 틀렸다 —
**같은 시험 안에서도 시편에 따라 칸이 갈린다.**

실측 근거:

  - DMA 실파일 172개 **전부**에 장비가 적은 `Geometry name` 이 있고, 155개가
    `3 Point Bending Clamp` 였다. 3점 굽힘은 지지 간격이 필요하고 인장 필름
    클램프는 필요 없다.
  - Zwick `.tra` 가 주는 것은 `a0`(두께)·`b0`(폭) 로 **평판형**이다. 환봉형은
    `d0`(직경) 하나이고 폭·두께가 아예 없다. ASTM E8 은 sheet·plate·round 를
    한 규격 안에 담는다.
  - 그 방증으로 `specimens` 표에는 지금도 직경 컬럼이 없다 — 66 은 환봉 시편을
    표현하지 못한다.

## 두 층으로 나눈다

    시편 분류 (기준정보 축)   그 분류의 규격이면 **예외 없이** 갖는 기본 칸
    시편 규격 (그 아래 값)    거기에 자기만의 칸을 더한다(`extra_fields`)

분류는 규격의 **상위 값**이다 — 축 계층 기계를 그대로 쓴다(`grade` 의 부모가
`category` 이듯). 그래서 앞 리비전의 `kind` 컬럼이 필요 없어져 지운다.

Revision ID: a5841204ffdb
Revises: fda81ee7706e
Create Date: 2026-08-22 09:12:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5841204ffdb"
down_revision: str | Sequence[str] | None = "fda81ee7706e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: 기본 분류와 그 **기본 칸**. (키, 이름, 필수, 도움말)
#:
#: **최소로 둔다.** 그 분류의 규격이면 예외 없이 갖는 것만 — 인장 환봉에는
#: 폭·두께가 없고 DMA 인장 필름에는 지지 간격이 없다. 그런 것은 규격이 자기
#: 칸으로 더한다.
CATEGORIES: dict[str, list[tuple[str, str, bool, str | None]]] = {
    "인장": [
        (
            "gauge_length",
            "게이지 길이",
            True,
            "변위를 이 길이로 나눠 변형률을 만듭니다. 평판이든 환봉이든 있습니다.",
        ),
        ("total_length", "전체 길이", False, None),
    ],
    "DMA": [
        (
            "free_length",
            "자유 길이",
            True,
            "클램프 사이의 길이. 계산에 들어가는 것은 전체 길이가 아니라 이 값입니다.",
        ),
        ("width", "폭", True, None),
        ("thickness", "두께", True, None),
    ],
}

#: 앞 리비전이 값에 적어 둔 시험 종류 키 → 분류 값.
FROM_KIND = {"tensile": "인장", "dma_sweep": "DMA"}


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # **스키마를 바꾸기 전에 읽는다.** 아래에서 `kind` 컬럼이 지워지므로, 여기서
    # 잡아 두지 않으면 규격이 어느 분류의 것이었는지 알 수 없다.
    old_kinds = {
        row[0]: row[1]
        for row in bind.execute(
            sa.text("SELECT id, kind FROM vocabulary_terms WHERE kind IS NOT NULL")
        )
    }

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specimen_fields",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category_term_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("dimension", sa.String(length=20), nullable=False),
        sa.Column("si_unit", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("help", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["category_term_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_specimen_fields_category_term_id_vocabulary_terms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specimen_fields")),
        sa.UniqueConstraint("category_term_id", "key", name="uq_specimen_fields_key"),
    )
    op.create_index(
        op.f("ix_specimen_fields_category_term_id"),
        "specimen_fields",
        ["category_term_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_test_specimen_fields_test_type_id"), table_name="test_specimen_fields"
    )
    op.drop_table("test_specimen_fields")
    op.add_column(
        "vocabulary_terms",
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_vocabulary_terms_kind"), table_name="vocabulary_terms")
    op.drop_column("vocabulary_terms", "kind")
    # ### end Alembic commands ###

    # --- 여기부터는 데이터다. **이미 도는 DB 를 위한 것.** -------------------
    #
    # `definitions.py` 가 같은 것을 심지만 그건 **새 DB** 를 위한 것이다(시드는
    # 이미 있는 것을 건드리지 않는다).

    # 1) 시편 분류 축을 만들고, 규격을 그 아래로 옮긴다.
    bind.execute(
        sa.text(
            "INSERT INTO vocabularies (id, slug, label, entry_policy, sort_order, "
            "                          parent_slug, attribute_source, created_at) "
            "VALUES (gen_random_uuid(), 'specimen_category', '시편 분류', 'open', 38, "
            "        NULL, NULL, now()) "
            "ON CONFLICT (slug) DO NOTHING"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE vocabularies SET parent_slug = 'specimen_category', "
            "       attribute_source = 'parent' WHERE slug = 'specimen_standard'"
        )
    )
    axis_id = bind.execute(
        sa.text("SELECT id FROM vocabularies WHERE slug = 'specimen_category'")
    ).scalar()

    # 2) 기본 분류와 그 기본 칸.
    term_ids: dict[str, object] = {}
    for value, fields in CATEGORIES.items():
        bind.execute(
            sa.text(
                "INSERT INTO vocabulary_terms (id, vocabulary_id, value, normalized, "
                "                              status, usage_count, attributes, "
                "                              extra_fields, created_at) "
                "VALUES (gen_random_uuid(), :axis, :value, :norm, 'active', 0, "
                "        '{}'::jsonb, '[]'::jsonb, now()) "
                "ON CONFLICT (vocabulary_id, normalized) DO NOTHING"
            ),
            {"axis": axis_id, "value": value, "norm": value.lower()},
        )
        term_ids[value] = bind.execute(
            sa.text(
                "SELECT id FROM vocabulary_terms "
                "WHERE vocabulary_id = :axis AND normalized = :norm"
            ),
            {"axis": axis_id, "norm": value.lower()},
        ).scalar()

        for order, (key, label, required, help_text) in enumerate(fields):
            bind.execute(
                sa.text(
                    "INSERT INTO specimen_fields (id, category_term_id, key, label, "
                    "                             dimension, si_unit, is_required, "
                    "                             help, sort_order) "
                    "VALUES (gen_random_uuid(), :term, :key, :label, 'length', 'm', "
                    "        :required, :help, :sort_order) "
                    "ON CONFLICT (category_term_id, key) DO NOTHING"
                ),
                {
                    "term": term_ids[value],
                    "key": key,
                    "label": label,
                    "required": required,
                    "help": help_text,
                    "sort_order": order * 10,
                },
            )

    # 3) 이미 있던 규격을 분류 아래로. 앞 리비전이 적어 둔 `kind` 를 보고 잇는다.
    for term_id, kind in old_kinds.items():
        category = FROM_KIND.get(str(kind))
        if category is None or term_ids.get(category) is None:
            continue
        bind.execute(
            sa.text("UPDATE vocabulary_terms SET parent_term_id = :parent WHERE id = :id"),
            {"parent": term_ids[category], "id": term_id},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vocabulary_terms",
        sa.Column("kind", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_vocabulary_terms_kind"), "vocabulary_terms", ["kind"], unique=False
    )
    op.drop_column("vocabulary_terms", "extra_fields")
    op.create_table(
        "test_specimen_fields",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("test_type_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("dimension", sa.String(length=20), nullable=False),
        sa.Column("si_unit", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("help", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["test_type_id"],
            ["test_types.id"],
            name=op.f("fk_test_specimen_fields_test_type_id_test_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_specimen_fields")),
        sa.UniqueConstraint("test_type_id", "key", name="uq_test_specimen_fields_key"),
    )
    op.create_index(
        op.f("ix_test_specimen_fields_test_type_id"),
        "test_specimen_fields",
        ["test_type_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_specimen_fields_category_term_id"), table_name="specimen_fields")
    op.drop_table("specimen_fields")
    # ### end Alembic commands ###

    # 축은 되돌리지 않는다 — 사람이 만든 분류 값이 섞여 있을 수 있고, 그것을
    # 지우면 그 규격이 무엇이었는지 알 수 없게 된다.
    op.execute(
        "UPDATE vocabularies SET parent_slug = NULL, attribute_source = 'test_type' "
        "WHERE slug = 'specimen_standard'"
    )
