"""부서 계층

Revision ID: b2c21627d4f6
Revises: 16e6d2d1f6a5
Create Date: 2026-08-16 08:37:09.852752

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2c21627d4f6"
down_revision: Union[str, Sequence[str], None] = "16e6d2d1f6a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspaces", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.add_column(
        "workspaces", sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False)
    )
    op.create_index(op.f("ix_workspaces_parent_id"), "workspaces", ["parent_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_workspaces_parent_id_workspaces"),
        "workspaces",
        "workspaces",
        ["parent_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_workspaces_parent_id_workspaces"), "workspaces", type_="foreignkey"
    )
    op.drop_index(op.f("ix_workspaces_parent_id"), table_name="workspaces")
    op.drop_column("workspaces", "sort_order")
    op.drop_column("workspaces", "parent_id")
    # ### end Alembic commands ###
