"""강종 축

Revision ID: c15961e7444a
Revises: 44c8ab691a47
Create Date: 2026-08-21 02:40:59.580249

"""

from typing import Sequence, Union

import logging

from alembic import op
import sqlalchemy as sa

from app.modules.vocabulary.normalize import clean, compare_key

logger = logging.getLogger("alembic.runtime.migration")


# revision identifiers, used by Alembic.
revision: str = "c15961e7444a"
down_revision: Union[str, Sequence[str], None] = "44c8ab691a47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- 강종 축 ----------------------------------------------------------------
#
# **가장 큰 축이고 이득도 가장 크다.** `SECC`/`secc`/`S.E.C.C` 가 지금은 서로
# 다른 재료 셋을 만들고, 통계도 카드도 셋으로 갈린다.
#
# 다만 강종은 재료 이름을 만드는 값이라(ADR 0004) 백필에서 **표기를 바꾸면 안
# 된다.** 정규화가 이름을 바꿔 버리면 그 재료의 시료·시편·시험 이름이 전부
# 어긋난다. 그래서 값은 `clean` 한 것을 어휘에 넣되, 재료의 `grade` 문자열은
# 손대지 않는다 — 정리는 관리자가 이름 변경으로 한다(연쇄 변경이 함께 돈다).


def _seed_and_backfill_grade() -> None:
    bind = op.get_bind()
    bind.execute(
        sa.text(
            "INSERT INTO vocabularies (id, slug, label, entry_policy, sort_order)"
            " VALUES (gen_random_uuid(), 'grade', '강종', 'open', 5)"
        )
    )
    vocabulary_id = bind.execute(
        sa.text("SELECT id FROM vocabularies WHERE slug = 'grade'")
    ).scalar_one()

    rows = (
        bind.execute(
            sa.text(
                "SELECT DISTINCT grade FROM materials WHERE grade IS NOT NULL AND grade <> ''"
            )
        )
        .scalars()
        .all()
    )

    for raw in rows:
        key = compare_key(raw)
        value = clean(raw)
        if not key or value is None:
            continue
        existing = bind.execute(
            sa.text(
                "SELECT id FROM vocabulary_terms"
                " WHERE vocabulary_id = :vid AND normalized = :key"
            ),
            {"vid": vocabulary_id, "key": key},
        ).scalar()
        if existing is None:
            bind.execute(
                sa.text(
                    "INSERT INTO vocabulary_terms"
                    " (id, vocabulary_id, value, normalized, status, usage_count)"
                    " VALUES (gen_random_uuid(), :vid, :value, :key, 'active', 0)"
                ),
                {"vid": vocabulary_id, "value": value, "key": key},
            )

    filled = bind.execute(
        sa.text(
            """
            UPDATE materials AS m
               SET grade_term_id = t.id
              FROM vocabulary_terms AS t
             WHERE t.vocabulary_id = :vid
               AND t.normalized = lower(btrim(m.grade))
               AND m.grade IS NOT NULL
            """
        ),
        {"vid": vocabulary_id},
    ).rowcount
    bind.execute(
        sa.text(
            """
            UPDATE vocabulary_terms AS t
               SET usage_count = (SELECT count(*) FROM materials
                                   WHERE grade_term_id = t.id AND deleted_at IS NULL)
             WHERE t.vocabulary_id = :vid
            """
        ),
        {"vid": vocabulary_id},
    )
    terms = bind.execute(
        sa.text("SELECT count(*) FROM vocabulary_terms WHERE vocabulary_id = :vid"),
        {"vid": vocabulary_id},
    ).scalar_one()
    logger.info("강종 어휘 %s종 · 재료 %s건 연결", terms, filled)

    # **표기가 갈린 것을 말해 준다.** 여기서 합치지 않는다 — 합치면 재료 이름이
    # 바뀌고 그 파급을 마이그레이션이 조용히 결정하는 셈이다.
    clashes = bind.execute(
        sa.text(
            """
            SELECT t.value, count(DISTINCT m.grade)
              FROM vocabulary_terms AS t
              JOIN materials AS m ON m.grade_term_id = t.id
             WHERE t.vocabulary_id = :vid
             GROUP BY t.id, t.value
            HAVING count(DISTINCT m.grade) > 1
            """
        ),
        {"vid": vocabulary_id},
    ).all()
    for value, n in clashes:
        logger.warning(
            "강종 %r 를 %s가지 표기가 가리킵니다 — 어휘 관리에서 이름을 고치면 "
            "재료 이름이 함께 정리됩니다.",
            value,
            n,
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("materials", sa.Column("grade_term_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_materials_grade_term_id"), "materials", ["grade_term_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_materials_grade_term_id_vocabulary_terms"),
        "materials",
        "vocabulary_terms",
        ["grade_term_id"],
        ["id"],
    )
    # ### end Alembic commands ###
    _seed_and_backfill_grade()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_materials_grade_term_id_vocabulary_terms"), "materials", type_="foreignkey"
    )
    op.drop_index(op.f("ix_materials_grade_term_id"), table_name="materials")
    op.drop_column("materials", "grade_term_id")
    # ### end Alembic commands ###
