"""accounts: is_active를 status로 교체, 가입 승인 필드 추가

Revision ID: c3c6a6277ea8
Revises: 333ba1d45ef5
Create Date: 2026-08-15 01:15:19.407468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3c6a6277ea8"
down_revision: Union[str, Sequence[str], None] = "333ba1d45ef5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 새 컬럼의 server_default 는 'pending' 이다. 그대로 두면 **기존 계정이 전부
    # 승인 대기가 되어 관리자까지 잠긴다.** 그래서 컬럼을 추가한 뒤 기존
    # is_active 값을 상태로 옮기고, is_active 는 그 다음에 지운다.
    op.add_column(
        "users",
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
    )
    op.execute(
        "UPDATE users SET status = CASE WHEN is_active THEN 'active' ELSE 'suspended' END"
    )
    op.add_column("users", sa.Column("requested_workspace_id", sa.UUID(), nullable=True))
    op.add_column("users", sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("decided_by_id", sa.UUID(), nullable=True))
    op.add_column("users", sa.Column("decision_note", sa.Text(), nullable=True))
    op.create_foreign_key(
        op.f("fk_users_decided_by_id_users"),
        "users",
        "users",
        ["decided_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_users_requested_workspace_id_workspaces"),
        "users",
        "workspaces",
        ["requested_workspace_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # 되돌릴 때도 값을 옮긴다. pending 은 불리언으로 표현할 수 없으므로 비활성으로
    # 접힌다 — 되돌린 뒤 승인 대기 계정은 관리자가 다시 살펴야 한다.
    op.execute("UPDATE users SET is_active = (status = 'active')")
    op.drop_constraint(
        op.f("fk_users_requested_workspace_id_workspaces"), "users", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_users_decided_by_id_users"), "users", type_="foreignkey")
    op.drop_column("users", "decision_note")
    op.drop_column("users", "decided_by_id")
    op.drop_column("users", "decided_at")
    op.drop_column("users", "requested_workspace_id")
    op.drop_column("users", "status")
    # ### end Alembic commands ###
