"""시험 원본 교체 — 언제 바꿨고 무엇이 왔었는지 (VOC 2026-09-13)

Revision ID: db4c6752ea62
Revises: 000ce19f07d7
Create Date: 2026-09-13 03:51:02.963613

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "db4c6752ea62"
down_revision: Union[str, Sequence[str], None] = "000ce19f07d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_runs", sa.Column("source_replaced_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "test_runs",
        sa.Column(
            "source_history",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_runs", "source_history")
    op.drop_column("test_runs", "source_replaced_at")
    # ### end Alembic commands ###
