"""감사 기록에 클라이언트

**사람이 한 것과 AI 가 한 것을 가르는 열.** MCP 서버는 진작부터 `X-Client: mcp` 를
보내고 있었는데 백엔드가 안 읽었다 — 쓰기 도구를 늘리기 전에 이것부터 둔다.

`catalog_links` 제약 개명은 일부러 뺐다(이 변경과 상관없는 남의 표다).

Revision ID: dfbc9445a743
Revises: e3f66a505405
Create Date: 2026-09-09 21:52:56.583072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfbc9445a743"
down_revision: Union[str, Sequence[str], None] = "e3f66a505405"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_entries",
        sa.Column("client", sa.String(length=20), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_entries", "client")
    # ### end Alembic commands ###
