"""결과 계산식 연결표 — 「이 값 어느 식으로 계산됐나」 를 그래프가 걷게(4단계, 2026-09-16).

이미 있는 결과는 `stages[].plugin = "formula.<key>"` 에서 되짚어 채운다. 식 판은 그때 것을
모르니 **지금 판**으로 적는다 — 옛 결과의 판은 stages 의 `version` 이 정본이다.

Revision ID: e004e443d2fb
Revises: 8a95c7e22b4e
Create Date: 2026-09-16 20:48:51.920439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e004e443d2fb"
down_revision: Union[str, Sequence[str], None] = "8a95c7e22b4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processing_result_formulas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("result_id", sa.UUID(), nullable=False),
        sa.Column("formula_id", sa.UUID(), nullable=False),
        sa.Column("formula_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["formula_id"],
            ["formulas.id"],
            name=op.f("fk_processing_result_formulas_formula_id_formulas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["processing_results.id"],
            name=op.f("fk_processing_result_formulas_result_id_processing_results"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_result_formulas")),
    )
    op.create_index(
        op.f("ix_processing_result_formulas_formula_id"),
        "processing_result_formulas",
        ["formula_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processing_result_formulas_result_id"),
        "processing_result_formulas",
        ["result_id"],
        unique=False,
    )
    op.create_index(
        "uq_processing_result_formulas_pair",
        "processing_result_formulas",
        ["result_id", "formula_id"],
        unique=True,
    )
    # 백필 — stages JSON 의 식 단계에서.
    op.execute(
        sa.text(
            """
            INSERT INTO processing_result_formulas (id, result_id, formula_id, formula_version)
            SELECT gen_random_uuid(), r.id, f.id, f.version
            FROM processing_results r
            CROSS JOIN LATERAL jsonb_array_elements(r.stages) AS stage
            JOIN formulas f ON f.key = substr(stage->>'plugin', length('formula.') + 1)
            WHERE stage->>'plugin' LIKE 'formula.%'
            ON CONFLICT DO NOTHING
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_processing_result_formulas_pair", table_name="processing_result_formulas"
    )
    op.drop_index(
        op.f("ix_processing_result_formulas_result_id"),
        table_name="processing_result_formulas",
    )
    op.drop_index(
        op.f("ix_processing_result_formulas_formula_id"),
        table_name="processing_result_formulas",
    )
    op.drop_table("processing_result_formulas")
    # ### end Alembic commands ###
