"""재료 모델 파라미터 집합

Anand 9개·Prony 항·Ogden 계수처럼 **여럿이 한 벌이어야 뜻이 있는** 값이 사는 자리
(ADR 0029). 값 하나짜리는 선언 물성이 담고, 묶음은 여기가 담는다. 카드는 이것을
**인용**한다 — 카드에 바로 넣으면 물성 탭에서 안 보이고 후보를 여럿 둘 수 없다.

**`catalog_links` 제약 개명은 일부러 뺐다.** autogenerate 가 함께 냈는데(옛 이름과
현재 규칙이 다르다) 이 변경과 상관없는 남의 표다 — 섞어 넣으면 되돌릴 때 무엇 때문에
되돌리는지 알 수 없다. 필요하면 그것만 따로 낸다.

Revision ID: e3f66a505405
Revises: 888bca60a86b
Create Date: 2026-09-08 23:31:05.155847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e3f66a505405"
down_revision: Union[str, Sequence[str], None] = "888bca60a86b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "material_parameter_sets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("property_key", sa.String(length=120), nullable=True),
        sa.Column("origin", sa.String(length=20), nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=False),
        sa.Column("source_detail", sa.Text(), nullable=True),
        sa.Column("quality_tier", sa.Integer(), nullable=True),
        sa.Column("terms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_material_parameter_sets_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_material_parameter_sets_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_parameter_sets")),
        sa.UniqueConstraint(
            "material_id", "model", "source_ref", name="uq_material_parameter_sets"
        ),
    )
    op.create_index(
        op.f("ix_material_parameter_sets_material_id"),
        "material_parameter_sets",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_material_parameter_sets_model"),
        "material_parameter_sets",
        ["model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_material_parameter_sets_property_key"),
        "material_parameter_sets",
        ["property_key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_material_parameter_sets_property_key"), table_name="material_parameter_sets"
    )
    op.drop_index(
        op.f("ix_material_parameter_sets_model"), table_name="material_parameter_sets"
    )
    op.drop_index(
        op.f("ix_material_parameter_sets_material_id"), table_name="material_parameter_sets"
    )
    op.drop_table("material_parameter_sets")
    # ### end Alembic commands ###
