"""묶음을 행으로 남긴다 — 여러 시험을 묶어 만든 것.

## 왜 표를 새로 두나

점탄성이 `master_curves` 라는 **전용 표**로 이 일을 하고 있었다. 다음 물성이 오면
또 만들어야 했다 — 피로 S-N(시편 수십 개를 지나는 회귀), 크리프(조건별 여러
시험)가 전부 같은 모양이다.

무엇을 묶는지는 **플러그인이 정한다**(`registry.register(kind="grouping")`). 이
표는 「누구를 묶어 무엇이 나왔나」 만 안다.

## 불변이다

처리 결과와 같다. 방법을 바꿔 다시 묶으면 **새 행**이 생기고, 앞의 것은 그때의
방법(`options`)과 구성원(`members`)을 그대로 들고 남는다 — 「왜 이 값이 이래」 에
답하려면 그 스냅샷이 있어야 한다.

## 기존 마스터커브는 안 건드린다

`master_curves`·`prony_fits` 는 그대로 둔다. **돌아가는 것을 옮기지 않는다** —
새 개념만 일반형으로 두고, 그것이 두 번째 사용자를 얻을 때 옮길지 정한다.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e51ac62f775e"
down_revision: Union[str, Sequence[str], None] = "d8f4a17c2e60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("plugin_id", sa.String(length=80), nullable=False),
        sa.Column("plugin_version", sa.String(length=20), nullable=False),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "members",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "used",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_group_results_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_group_results_material_id_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_group_results_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_results")),
    )
    op.create_index(
        op.f("ix_group_results_created_at"), "group_results", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_group_results_created_by_id"),
        "group_results",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        "ix_group_results_material_created",
        "group_results",
        ["material_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_results_material_id"), "group_results", ["material_id"], unique=False
    )
    op.create_index(
        op.f("ix_group_results_plugin_id"), "group_results", ["plugin_id"], unique=False
    )
    op.create_index(
        op.f("ix_group_results_workspace_id"), "group_results", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_group_results_workspace_id"), table_name="group_results")
    op.drop_index(op.f("ix_group_results_plugin_id"), table_name="group_results")
    op.drop_index(op.f("ix_group_results_material_id"), table_name="group_results")
    op.drop_index("ix_group_results_material_created", table_name="group_results")
    op.drop_index(op.f("ix_group_results_created_by_id"), table_name="group_results")
    op.drop_index(op.f("ix_group_results_created_at"), table_name="group_results")
    op.drop_table("group_results")
    # ### end Alembic commands ###
