"""장비 기준정보 문자열 짝

Revision ID: e913af29ac90
Revises: 28ff5e37afe1
Create Date: 2026-09-07 23:24:06.046624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e913af29ac90"
down_revision: Union[str, Sequence[str], None] = "28ff5e37afe1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "equipment_units", sa.Column("instrument_type", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "equipment_units", sa.Column("instrument", sa.String(length=120), nullable=True)
    )
    op.add_column("equipment_units", sa.Column("lab", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("equipment_units", "lab")
    op.drop_column("equipment_units", "instrument")
    op.drop_column("equipment_units", "instrument_type")
    # ### end Alembic commands ###
