"""마스터커브와 Prony 적합

Revision ID: e96990a6b281
Revises: 7a402bba2eca
Create Date: 2026-08-21 22:23:06.157817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e96990a6b281'
down_revision: Union[str, Sequence[str], None] = '7a402bba2eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_curves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_run_id', sa.UUID(), nullable=False),
    sa.Column('source_curve_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_temperature_k', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shifts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('minimum_frequency_hz', sa.Float(), nullable=False),
    sa.Column('maximum_frequency_hz', sa.Float(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_master_curves_created_by_id_users')),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], name=op.f('fk_master_curves_test_run_id_test_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_curves'))
    )
    op.create_index(op.f('ix_master_curves_test_run_id'), 'master_curves', ['test_run_id'], unique=False)
    op.create_table('prony_fits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_curve_id', sa.UUID(), nullable=False),
    sa.Column('equilibrium_pa', sa.Float(), nullable=False),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_rmse', sa.Float(), nullable=False),
    sa.Column('bic', sa.Float(), nullable=False),
    sa.Column('at_bound', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_prony_fits_created_by_id_users')),
    sa.ForeignKeyConstraint(['master_curve_id'], ['master_curves.id'], name=op.f('fk_prony_fits_master_curve_id_master_curves'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prony_fits'))
    )
    op.create_index(op.f('ix_prony_fits_master_curve_id'), 'prony_fits', ['master_curve_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prony_fits_master_curve_id'), table_name='prony_fits')
    op.drop_table('prony_fits')
    op.drop_index(op.f('ix_master_curves_test_run_id'), table_name='master_curves')
    op.drop_table('master_curves')
    # ### end Alembic commands ###
