"""곡선 종류

Revision ID: f00ab8469618
Revises: a06c3890ff83
Create Date: 2026-08-16 11:30:21.820798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f00ab8469618"
down_revision: Union[str, Sequence[str], None] = "a06c3890ff83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "curves",
        sa.Column("kind", sa.String(length=20), server_default="measured", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("curves", "kind")
    # ### end Alembic commands ###
