"""export_profiles — 솔버 덱 정의를 데이터로 둔다(ADR 0023 2단계)

autogenerate 가 `guide_sections` 의 trgm 인덱스 둘을 「없어졌다」 고 넣었는데
**지웠다** — 모델에서 `postgresql_using='gin'` 을 못 읽어 매번 그렇게 본다.
그대로 두면 이 마이그레이션이 가이드 검색을 죽인다.

Revision ID: f5ddedc5ac97
Revises: 32f94428907c
Create Date: 2026-08-30 10:10:21.240820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f5ddedc5ac97"
down_revision: Union[str, Sequence[str], None] = "32f94428907c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "export_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_workspace_id", sa.UUID(), nullable=True),
        sa.Column(
            "definition",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_export_profiles_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_export_profiles_owner_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_profiles")),
    )
    op.create_index(
        op.f("ix_export_profiles_created_by_id"),
        "export_profiles",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_export_profiles_deleted_at"), "export_profiles", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_export_profiles_key"), "export_profiles", ["key"], unique=False)
    op.create_index(
        op.f("ix_export_profiles_owner_workspace_id"),
        "export_profiles",
        ["owner_workspace_id"],
        unique=False,
    )
    op.create_index(
        "uq_export_profiles_scope_key",
        "export_profiles",
        ["owner_workspace_id", "key"],
        unique=True,
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_export_profiles_scope_key",
        table_name="export_profiles",
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_export_profiles_owner_workspace_id"), table_name="export_profiles")
    op.drop_index(op.f("ix_export_profiles_key"), table_name="export_profiles")
    op.drop_index(op.f("ix_export_profiles_deleted_at"), table_name="export_profiles")
    op.drop_index(op.f("ix_export_profiles_created_by_id"), table_name="export_profiles")
    op.drop_table("export_profiles")
    # ### end Alembic commands ###
