"""수집 체계 소프트 삭제

Revision ID: f69bb89be861
Revises: c9d4e2f7a1b6
Create Date: 2026-08-29 22:14:59.456022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f69bb89be861"
down_revision: Union[str, Sequence[str], None] = "c9d4e2f7a1b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    **가이드의 trgm 인덱스를 지우는 줄 넷을 손으로 걷어 냈다.** autogenerate 가
    매번 그것을 넣으려 든다 — 모델이 선언하지 않고 마이그레이션에서만 만든
    인덱스라 alembic 이 「없어야 할 것」 으로 본다(`b3e8f1a2c9d4`). 그대로
    두면 이 배포에서 **핸드북 검색이 통째로 느려진다.**
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "format_profiles", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_constraint(op.f("uq_format_profiles_scope_key"), "format_profiles", type_="unique")
    op.create_index(
        "uq_format_profiles_scope_key",
        "format_profiles",
        ["owner_workspace_id", "key"],
        unique=True,
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_format_profiles_deleted_at"), "format_profiles", ["deleted_at"], unique=False
    )
    op.add_column(
        "processing_recipes",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_constraint(
        op.f("uq_processing_recipes_scope_key"), "processing_recipes", type_="unique"
    )
    op.create_index(
        "uq_processing_recipes_scope_key",
        "processing_recipes",
        ["owner_workspace_id", "key"],
        unique=True,
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_processing_recipes_deleted_at"),
        "processing_recipes",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "test_types", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index(op.f("ix_test_types_key"), table_name="test_types")
    op.create_index(op.f("ix_test_types_key"), "test_types", ["key"], unique=False)
    op.create_index(
        op.f("ix_test_types_deleted_at"), "test_types", ["deleted_at"], unique=False
    )
    op.create_index(
        "uq_test_types_key",
        "test_types",
        ["key"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_test_types_key",
        table_name="test_types",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_test_types_deleted_at"), table_name="test_types")
    op.drop_index(op.f("ix_test_types_key"), table_name="test_types")
    op.create_index(op.f("ix_test_types_key"), "test_types", ["key"], unique=True)
    op.drop_column("test_types", "deleted_at")
    op.drop_index(op.f("ix_processing_recipes_deleted_at"), table_name="processing_recipes")
    op.drop_index(
        "uq_processing_recipes_scope_key",
        table_name="processing_recipes",
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_processing_recipes_scope_key"),
        "processing_recipes",
        ["owner_workspace_id", "key"],
        postgresql_nulls_not_distinct=True,
    )
    op.drop_column("processing_recipes", "deleted_at")
    op.drop_index(op.f("ix_format_profiles_deleted_at"), table_name="format_profiles")
    op.drop_index(
        "uq_format_profiles_scope_key",
        table_name="format_profiles",
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_format_profiles_scope_key"),
        "format_profiles",
        ["owner_workspace_id", "key"],
        postgresql_nulls_not_distinct=True,
    )
    op.drop_column("format_profiles", "deleted_at")
    # ### end Alembic commands ###
