"""적용 제품 부위 축

Revision ID: faaa94df2735
Revises: 82ac9bab9b5c
Create Date: 2026-08-21 09:18:25.283924

"""

from typing import Sequence, Union

import logging

from alembic import op
import sqlalchemy as sa

from app.modules.vocabulary.normalize import clean, compare_key

logger = logging.getLogger("alembic.runtime.migration")


# revision identifiers, used by Alembic.
revision: str = "faaa94df2735"
down_revision: Union[str, Sequence[str], None] = "82ac9bab9b5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("materials", sa.Column("applied_product_term_id", sa.UUID(), nullable=True))
    op.add_column("materials", sa.Column("applied_part_term_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_materials_applied_part_term_id"),
        "materials",
        ["applied_part_term_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_materials_applied_product_term_id"),
        "materials",
        ["applied_product_term_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_materials_applied_product_term_id_vocabulary_terms"),
        "materials",
        "vocabulary_terms",
        ["applied_product_term_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_materials_applied_part_term_id_vocabulary_terms"),
        "materials",
        "vocabulary_terms",
        ["applied_part_term_id"],
        ["id"],
    )
    # ### end Alembic commands ###
    _seed_and_backfill()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_materials_applied_part_term_id_vocabulary_terms"),
        "materials",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_materials_applied_product_term_id_vocabulary_terms"),
        "materials",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_materials_applied_product_term_id"), table_name="materials")
    op.drop_index(op.f("ix_materials_applied_part_term_id"), table_name="materials")
    op.drop_column("materials", "applied_part_term_id")
    op.drop_column("materials", "applied_product_term_id")
    # ### end Alembic commands ###
    # **심은 축도 걷어낸다.** 안 걷으면 되돌린 뒤에도 관리 화면에 아무도 안
    # 가리키는 축 둘이 남는다. 컬럼이 사라진 뒤라 이 값들을 가리키는 것은 없다.
    bind = op.get_bind()
    slugs = tuple(slug for slug, _label, _order in VOCABULARIES)
    bind.execute(
        sa.text(
            "DELETE FROM vocabulary_aliases WHERE vocabulary_id IN"
            " (SELECT id FROM vocabularies WHERE slug = ANY(:slugs))"
        ),
        {"slugs": list(slugs)},
    )
    bind.execute(
        sa.text(
            "DELETE FROM vocabulary_terms WHERE vocabulary_id IN"
            " (SELECT id FROM vocabularies WHERE slug = ANY(:slugs))"
        ),
        {"slugs": list(slugs)},
    )
    bind.execute(
        sa.text("DELETE FROM vocabularies WHERE slug = ANY(:slugs)"),
        {"slugs": list(slugs)},
    )


# --- 축 심기와 백필 ---------------------------------------------------------
#
# 2단계의 마지막 두 축. **용도는 재료의 성질이다**(전에는 시료에 있었다) —
# "도어 이너용 재료가 뭐가 있나" 가 집계 질문이 되려면 자유 문자열이면 안 된다.
#
# 부위를 제품 아래에 두지 않는다. 값 하나에 부모는 하나인데 `이너 패널` 은
# 도어에도 후드에도 쓰인다 — 붙이면 먼저 들어온 제품이 이긴다.

VOCABULARIES = [
    # slug, label, sort_order.  **둘 다 open.**
    ("product", "적용 제품", 60),
    ("part", "적용 부위", 70),
]

#: (축, 문자열 컬럼, FK 컬럼). 둘 다 `materials` 에 있다.
COLUMNS = [
    ("product", "applied_product", "applied_product_term_id"),
    ("part", "applied_part", "applied_part_term_id"),
]


def _seed_and_backfill() -> None:
    bind = op.get_bind()

    for slug, label, order in VOCABULARIES:
        bind.execute(
            sa.text(
                "INSERT INTO vocabularies (id, slug, label, entry_policy, sort_order)"
                " VALUES (gen_random_uuid(), :slug, :label, 'open', :order)"
                " ON CONFLICT (slug) DO NOTHING"
            ),
            {"slug": slug, "label": label, "order": order},
        )

    for slug, text_column, fk_column in COLUMNS:
        vocabulary_id = bind.execute(
            sa.text("SELECT id FROM vocabularies WHERE slug = :slug"), {"slug": slug}
        ).scalar_one()

        raws = (
            bind.execute(
                sa.text(
                    f"SELECT DISTINCT {text_column} FROM materials"
                    f" WHERE {text_column} IS NOT NULL AND {text_column} <> ''"
                )
            )
            .scalars()
            .all()
        )

        # **잇는 것도 파이썬으로 한다.** 2-1 은 값은 `compare_key` 로 만들고
        # 잇기는 SQL `lower(btrim())` 으로 했다. 그 둘은 같지 않아서(NFKC·제로폭·
        # 연속 공백) 눈에 안 보이는 문자가 든 값이 안 이어지고 경고만 남았다.
        # 만든 키로 그대로 이으면 그 틈이 없다.
        for raw in raws:
            key = compare_key(raw)
            value = clean(raw)
            if not key or value is None:
                logger.warning("materials.%s 의 %r 는 빈 값이라 건너뜁니다", text_column, raw)
                continue
            term_id = bind.execute(
                sa.text(
                    "SELECT id FROM vocabulary_terms"
                    " WHERE vocabulary_id = :vid AND normalized = :key"
                ),
                {"vid": vocabulary_id, "key": key},
            ).scalar()
            if term_id is None:
                term_id = bind.execute(
                    sa.text(
                        "INSERT INTO vocabulary_terms"
                        " (id, vocabulary_id, value, normalized, status, usage_count)"
                        " VALUES (gen_random_uuid(), :vid, :value, :key, 'active', 0)"
                        " RETURNING id"
                    ),
                    {"vid": vocabulary_id, "value": value, "key": key},
                ).scalar_one()
            bind.execute(
                sa.text(f"UPDATE materials SET {fk_column} = :tid WHERE {text_column} = :raw"),
                {"tid": term_id, "raw": raw},
            )

        # **표기는 안 바꾼다.** 정규화가 값을 고치면 마이그레이션이 조용히
        # 결정을 내린 셈이 된다 — 정리는 관리 화면에서 사람이 한다.
        leftover = bind.execute(
            sa.text(
                f"SELECT count(*) FROM materials"
                f" WHERE {text_column} IS NOT NULL AND {text_column} <> ''"
                f"   AND {fk_column} IS NULL"
            )
        ).scalar_one()
        if leftover:
            logger.warning("materials.%s 중 %s건을 못 옮겼습니다", text_column, leftover)

        bind.execute(
            sa.text(
                f"UPDATE vocabulary_terms AS t"
                f"   SET usage_count = (SELECT count(*) FROM materials"
                f"                       WHERE {fk_column} = t.id AND deleted_at IS NULL)"
                f" WHERE t.vocabulary_id = :vid"
            ),
            {"vid": vocabulary_id},
        )
