"""시편이 규격에서 치수를 물려받는다

## 왜

시편 41개 중 치수가 있는 것이 3개뿐이라 처리가 첫 단계에서 막혔다. 규격서에는
`ASTM E8 subsize = 게이지 길이 25 mm` 라고 적혀 있는데 그 값이 시스템 어디에도
없어서 사람이 시편마다 옮겨 적어야 했다.

## 두 컬럼

`specimens.dimensions`  실측 치수. 키는 그 시편의 **규격이 정한 칸 이름**이다.
                        고정 컬럼 셋(두께·폭·게이지 길이)으로는 환봉(직경 하나)
                        도 관(외경·내경)도 담을 수 없었다.

`vocabulary_terms.cross_section`
                        그 규격의 단면적 식(`matcore.specimen`). 평판은 폭 곱하기
                        두께, 환봉은 π(직경/2)². **틀리면 응력이 자릿수째로
                        어긋나는데 숫자는 그럴듯해 보인다.**

## 옛 컬럼은 그대로 둔다

`thickness_m`·`width_m`·`gauge_length_m` 은 안 지운다(ADR 0010 Expand 와 같은
단계). 읽는 쪽이 `dimensions` 를 먼저 보고 없으면 옛 컬럼을 본다 — 한 릴리스
동안 둘이 같은 말을 하는지 보고 나서 지운다.

**규격의 공칭을 시편 행에 복사하지 않는다.** 복사하면 그 순간 둘이 같아 보이고,
규격을 고쳐도 시편은 옛 값을 든 채 남는다. 빈 칸은 읽을 때 규격에서 온다.


Revision ID: faf0432b7b88
Revises: a5841204ffdb
Create Date: 2026-08-22 10:01:26.137430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "faf0432b7b88"
down_revision: Union[str, Sequence[str], None] = "a5841204ffdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specimens",
        sa.Column(
            "dimensions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "vocabulary_terms", sa.Column("cross_section", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vocabulary_terms", "cross_section")
    op.drop_column("specimens", "dimensions")
    # ### end Alembic commands ###
