"""VOC 게시판과 절차

## 왜

VOC 가 「낸 사람과 관리자만 보는 카드 + 답변 한 줄」 이었다. 같은 문제를 여럿이
따로 내고, 무엇이 고쳐졌는지는 낸 사람만 알고, 「접수됐나 → 보고 있나 → 됐나」 가
답변 한 줄에 뭉쳐 있어 중간 상태가 없었다(2026-09-11 요청).

## 무엇이 바뀌나

`voc_items.seq`        게시판 번호. 기존 건은 **등록 순서**로 매긴다 — Identity 를
                       그냥 붙이면 물리 순서로 매겨져 옛 건이 뒤섞인다.
`voc_items.status_at`  지금 상태가 된 때. 답변이 있던 건은 답변 시각, 없으면 등록 시각.
`voc_items.status_by_id`
`voc_events`           등록·상태 변경·댓글의 이력. 기존 건마다 등록 이벤트 하나를
                       만들고, 답변이 있던 건은 그 답변을 두 번째 이벤트로 옮긴다.

## 옛 자리는 둔다

`reply`·`replied_by_id`·`replied_at` 은 안 지운다(ADR 0010 Expand). 읽는 쪽은 더 안
본다 — 한 릴리스 동안 `voc_events` 가 같은 말을 하는지 보고 나서 지운다.

## 손대지 않은 것

autogenerate 가 `catalog_links` 의 unique 제약 이름 차이도 잡았다(`uq_catalog_links_material`
↔ `_material_id`). 이 이관의 일이 아니라 뺐다 — 남의 표를 이름 정리 김에 건드리면
그 표를 같은 시간에 고치는 사람과 충돌한다.

Revision ID: fc0ec59d424a
Revises: dfbc9445a743
Create Date: 2026-09-11 18:20:06.944135

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc0ec59d424a"
down_revision: Union[str, Sequence[str], None] = "dfbc9445a743"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "voc_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("by_id", sa.UUID(), nullable=True),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["by_id"],
            ["users.id"],
            name=op.f("fk_voc_events_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["voc_items.id"],
            name=op.f("fk_voc_events_item_id_voc_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_voc_events")),
    )
    op.create_index(op.f("ix_voc_events_at"), "voc_events", ["at"], unique=False)
    op.create_index(op.f("ix_voc_events_item_id"), "voc_events", ["item_id"], unique=False)

    # ── 번호: 등록 순서로 매기고, 그다음부터 Identity 가 잇는다 ──────────────────
    op.add_column("voc_items", sa.Column("seq", sa.Integer(), nullable=True))
    op.execute(
        """
        UPDATE voc_items AS v
        SET seq = numbered.n
        FROM (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS n FROM voc_items
        ) AS numbered
        WHERE numbered.id = v.id
        """
    )
    # Identity 는 NOT NULL 인 열에만 붙는다 — 번호를 다 매긴 뒤에 잠그고 붙인다.
    op.alter_column("voc_items", "seq", nullable=False)
    op.execute(
        """
        DO $$
        DECLARE next_seq integer;
        BEGIN
            SELECT COALESCE(MAX(seq), 0) + 1 INTO next_seq FROM voc_items;
            EXECUTE format(
                'ALTER TABLE voc_items ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                next_seq
            );
        END $$;
        """
    )
    op.create_unique_constraint(op.f("uq_voc_items_seq"), "voc_items", ["seq"])

    # ── 지금 상태가 된 때·사람 ───────────────────────────────────────────────
    op.add_column(
        "voc_items",
        sa.Column(
            "status_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("voc_items", sa.Column("status_by_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_voc_items_status_by_id_users"),
        "voc_items",
        "users",
        ["status_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.execute(
        """
        UPDATE voc_items
        SET status_at = COALESCE(replied_at, created_at),
            status_by_id = COALESCE(replied_by_id, created_by_id)
        """
    )

    # ── 이력: 등록 한 줄, 답변이 있었으면 그 줄 하나 더 ─────────────────────────
    op.execute(
        """
        INSERT INTO voc_events (id, item_id, at, by_id, from_status, to_status, note)
        SELECT gen_random_uuid(), id, created_at, created_by_id, NULL, 'open', NULL
        FROM voc_items
        """
    )
    op.execute(
        """
        INSERT INTO voc_events (id, item_id, at, by_id, from_status, to_status, note)
        SELECT gen_random_uuid(), id, COALESCE(replied_at, created_at), replied_by_id,
               'open', status, reply
        FROM voc_items
        WHERE reply IS NOT NULL
        """
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("fk_voc_items_status_by_id_users"), "voc_items", type_="foreignkey"
    )
    op.drop_column("voc_items", "status_by_id")
    op.drop_column("voc_items", "status_at")
    op.drop_constraint(op.f("uq_voc_items_seq"), "voc_items", type_="unique")
    op.drop_column("voc_items", "seq")
    op.drop_index(op.f("ix_voc_events_item_id"), table_name="voc_events")
    op.drop_index(op.f("ix_voc_events_at"), table_name="voc_events")
    op.drop_table("voc_events")
