"""시편 규격 치수 칸과 값 속성

시편 규격은 이름이 아니라 **치수 한 벌**이다 — `ASTM E8 subsize` 는 게이지 길이
25 mm · 평행부 폭 6 mm 를 뜻한다. 그런데 그 칸이 **시험 종류마다 다르다**:
인장 규격에는 어깨 반경이 있고 DMA 규격에는 지지 간격이 있다.

그래서 스키마를 시험 종류가 선언하고(`test_specimen_fields`), 기준정보 값은
자기가 어느 종류의 규격인지(`vocabulary_terms.kind`)와 치수(`attributes`)만
갖는다. 축은 자기 값이 속성을 갖는지 한 번만 적는다(`vocabularies.attribute_source`).

Revision ID: fda81ee7706e
Revises: e96990a6b281
Create Date: 2026-08-22 07:44:52.317072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fda81ee7706e"
down_revision: Union[str, Sequence[str], None] = "e96990a6b281"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_specimen_fields",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("test_type_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("dimension", sa.String(length=20), nullable=False),
        sa.Column("si_unit", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("help", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["test_type_id"],
            ["test_types.id"],
            name=op.f("fk_test_specimen_fields_test_type_id_test_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_specimen_fields")),
        sa.UniqueConstraint("test_type_id", "key", name="uq_test_specimen_fields_key"),
    )
    op.create_index(
        op.f("ix_test_specimen_fields_test_type_id"),
        "test_specimen_fields",
        ["test_type_id"],
        unique=False,
    )
    op.add_column(
        "vocabularies", sa.Column("attribute_source", sa.String(length=20), nullable=True)
    )
    op.add_column("vocabulary_terms", sa.Column("kind", sa.String(length=50), nullable=True))
    op.add_column(
        "vocabulary_terms",
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_vocabulary_terms_kind"), "vocabulary_terms", ["kind"], unique=False
    )
    # ### end Alembic commands ###

    # --- 여기부터는 데이터다. **이미 도는 DB 를 위한 것.** -------------------
    #
    # `definitions.py` 가 같은 것을 심지만 그건 **새 DB** 를 위한 것이다(시드는
    # 이미 있는 것을 건드리지 않는다). 운영 DB 에는 `specimen_standard` 축과
    # 인장·DMA 종류가 이미 있으므로 여기서 채운다.
    op.execute(
        "UPDATE vocabularies SET attribute_source = 'test_type' "
        "WHERE slug = 'specimen_standard'"
    )

    #: (시험 종류 key, [(칸 key, 이름, 차원, SI 단위, 필수, 도움말)])
    fields = {
        "tensile": [
            (
                "gauge_length",
                "게이지 길이",
                "length",
                "m",
                True,
                "변위를 이 길이로 나눠 변형률을 만듭니다. 규격이 정하는 값입니다.",
            ),
            ("width", "평행부 폭", "length", "m", True, "하중을 나눌 단면의 폭."),
            (
                "thickness",
                "두께",
                "length",
                "m",
                False,
                "규격이 정하지 않는 것이 보통입니다 — 소재 두께가 그대로 시편 두께입니다.",
            ),
            ("parallel_length", "평행부 길이", "length", "m", False, None),
            ("total_length", "전체 길이", "length", "m", False, None),
            (
                "shoulder_radius",
                "어깨 반경",
                "length",
                "m",
                False,
                "평행부와 그립부를 잇는 곡률. 작으면 그 자리에서 끊어집니다.",
            ),
            ("grip_width", "그립부 폭", "length", "m", False, None),
        ],
        "dma_sweep": [
            (
                "free_length",
                "자유 길이",
                "length",
                "m",
                True,
                "클램프 사이의 길이. 변형 계산에 들어가는 것은 전체 길이가 아니라 이 값입니다.",
            ),
            ("width", "폭", "length", "m", True, None),
            ("thickness", "두께", "length", "m", True, None),
            (
                "span",
                "지지 간격",
                "length",
                "m",
                False,
                "3점·단순 굽힘 모드에서 지지점 사이 거리. 인장·전단 모드에는 없습니다.",
            ),
            ("total_length", "전체 길이", "length", "m", False, None),
        ],
    }

    bind = op.get_bind()
    for type_key, rows in fields.items():
        type_id = bind.execute(
            sa.text("SELECT id FROM test_types WHERE key = :key"), {"key": type_key}
        ).scalar()
        if type_id is None:
            # 그 종류를 아직 안 쓰는 설치도 있다. 없으면 넘어간다 —
            # `definitions.py` 가 나중에 만들 때 같이 심는다.
            continue
        for order, (key, label, dimension, si_unit, required, help_text) in enumerate(rows):
            bind.execute(
                sa.text(
                    "INSERT INTO test_specimen_fields "
                    "(id, test_type_id, key, label, dimension, si_unit, is_required, "
                    " help, sort_order) "
                    "VALUES (gen_random_uuid(), :type_id, :key, :label, :dimension, "
                    "        :si_unit, :required, :help, :sort_order) "
                    "ON CONFLICT (test_type_id, key) DO NOTHING"
                ),
                {
                    "type_id": type_id,
                    "key": key,
                    "label": label,
                    "dimension": dimension,
                    "si_unit": si_unit,
                    "required": required,
                    "help": help_text,
                    "sort_order": order * 10,
                },
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vocabulary_terms_kind"), table_name="vocabulary_terms")
    op.drop_column("vocabulary_terms", "attributes")
    op.drop_column("vocabulary_terms", "kind")
    op.drop_column("vocabularies", "attribute_source")
    op.drop_index(
        op.f("ix_test_specimen_fields_test_type_id"), table_name="test_specimen_fields"
    )
    op.drop_table("test_specimen_fields")
    # ### end Alembic commands ###
